### ISSUE TITLE
Parameters changes to upper case

### ISSUE THREAD

**Issue by melund** [pyomeca/ezc3d#100]
It looks like ezc3d changes parameters to upper case when I read in a c3d file. 

Is this a bug or intended?. 

Here is a view from before:
![image](https://user-images.githubusercontent.com/1038978/70048851-958fe000-15cb-11ea-8197-d9567db1f519.png)

And after the file has been through ezc3d:
![image](https://user-images.githubusercontent.com/1038978/70048905-b2c4ae80-15cb-11ea-9be2-3e5686ca5ff4.png)

**Comment by pariterre** [comment]
Hello!
This is actually intended, but not necessary. The standard suggest to write them upper case but doesn't say it has to. From a programmer perspective, it helps to prevents a user from overwriting a mandatory parameter (e.g. POINTS:LABELS), but it can be annoying..

Changing this should not be a problem, but I cannot decide which I prefer..

**Comment by melund** [comment]
I wouldn't mind if ezc3d always created parameters as upper-case. But if I load an existing c3d file to change a marker etc  and save it back to disk then all my parameters are suddenly transformed to upper case. So I can no longer use with other applications which expected the original name.

**Comment by pariterre** [comment]
I see the problem, I think the best way is to not force uppercase then. I'll make the fix!
