### ISSUE TITLE
Residual marker info lost after save

### ISSUE THREAD

**Issue by melund** [pyomeca/ezc3d#101]
The residual marker information seems to disappear when we I use ezc3d to save a file back to disk. 

I use the residual to detect when a marker drops out.

**Comment by pariterre** [comment]
Hi!
Do you use the last version of ezc3d? I thought I solved that issue previously! In any case, I'll have a quick look tomorrow

**Comment by pariterre** [comment]
Hum, I think I know
Are you using ezc3d from Python or MATLAB? It is possible that this information is discarded using the binder... I'll see what I can do!

**Comment by melund** [comment]
Good question. It was running on a remote computer. I will take a look to see if the version was upto date.

**Comment by melund** [comment]
I was using Python...

**Comment by pariterre** [comment]
Yup, I just looked at it and I confirm that I discard that information. 
I can change that so the values are preserved, and I think it makes sense. However, that means the data retrieved from `c3d['data']['points'] will no longer be 3d column-vector that can be used with an homogeneous matrix of transformation (the column of a specific point being "XYZ-1" that is with a 1 on the 4th component), but a generic "XYZ-R" with the residual on the 4th component.

**Comment by melund** [comment]
If that is a problem, then maybe there should be a different interface to this extra information. C3D files usually also contains both a CamMask and Sign variable in addition to the residual for every point.  Although I have never used CamMask and Sign for anything.

**Comment by pariterre** [comment]
That is not a technical problem per se, actually, I already made a successful test on my fork implementing it. However, this is more a usability interrogation that I have. As you said, not much people uses the camera masks info (probably due to the fact that it is limited to 7 cameras...). 
I could write this info in another tag (e.g. c3d['data']['points_residual']). My fear is that if someone tries to create a new C3D file from scratch, they will forget to fill this field...

On another topic, do you actually need the values of the residual? So far, I just interpret the "residual" part as a float effectively integrating the masks and residual information. If you need them, I will split them up. Otherwise, I think the most relevant part is the sign of that word (negative meaning that the point is invalid)

**Comment by melund** [comment]
I use some programs which looks at the residual value and interpret a -1 as a marker dropout. 

> I could write this info in another tag (e.g. c3d['data']['points_residual']). My fear is that if someone tries to create a new C3D file from scratch, they will forget to fill this field...

Most people would surely forget to set the `c3d['data']['points_residual']` when creating a new point. Couldn't it be set a default value if it wasn't specified by the user?

**Comment by melund** [comment]
@pariterre  It didn't seem to solve it :(

![image](https://user-images.githubusercontent.com/1038978/70718230-1c416d00-1cf0-11ea-98f4-e0ee6e2e84ae.png)
![image](https://user-images.githubusercontent.com/1038978/70718257-2cf1e300-1cf0-11ea-8656-50ac542310b1.png)

**Comment by pariterre** [comment]
oh.. I'll have a second look.. sorry about that!

**Comment by pariterre** [comment]
This Issue is finally addressed here: #105

**Comment by marnunez** [comment]
Hi @pariterre! Have you considered using [numpy masked arrays](https://docs.scipy.org/doc/numpy/reference/maskedarray.html) for the "XYZ-R" format? It looks like the tool for the job.

**Comment by pariterre** [comment]
@marnunez 
That is an interesting point. I am 90% happy with what I have done using the extra tag. It has the advantage to be standardize with the MATLAB API. @melund do you have a preference?

**Comment by melund** [comment]
No. I don't have any preferences. I thinks others could decide.

**Comment by pariterre** [comment]
Ok, lets keep the extra tag then. I'll keep in mind these masked data though I may change my mind in the future!
Thanks for pointing this out @marnunez I did not know this feature!
