### ISSUE TITLE
Data are different when read on MacOs

### ISSUE THREAD

**Issue by romainmartinez** [pyomeca/ezc3d#106]
The data look different when a c3d is read on Linux and Windows compared to MacOs as shown in [this test](https://github.com/romainmartinez/motion/runs/399610948).

Here is a code snippet to reproduce the issue, with [this c3d](https://github.com/pyomeca/pyomeca/blob/dev/tests/data/markers_analogs.c3d): 

```python
c3d = ezc3d.c3d("markers_analogs.c3d")
array = c3d["data"]["points"]
decimal = 6

np.testing.assert_array_equal(
    x=array.shape, y=(4, 51, 580), err_msg="Shape does not match"
)
raveled = array.ravel()
np.testing.assert_array_almost_equal(
    x=raveled[0],
    y=44.16278839111328,
    decimal=decimal,
)
np.testing.assert_array_almost_equal(
    x=raveled[-1], y=1.0, decimal=decimal,
)
np.testing.assert_array_almost_equal(
    x=np.nanmean(array),
    y=362.2979849093196,
    decimal=decimal
)
np.testing.assert_array_almost_equal(
    x=np.nanmedian(array),
    y=337.7519226074219,
    decimal=decimal
)
np.testing.assert_allclose(
    actual=np.nansum(array),
    desired=42535594.91827867,
    rtol=0.05
)
np.testing.assert_array_equal(x=np.isnan(array).sum(), y=915)
```

**Comment by romainmartinez** [comment]
Funny thing is, Macos replaces NaN with 0's. I made a temporary fix with `array[array == 0] = np.nan`. 

If the problem persists over time, we should do a fix I guess?

**Comment by pariterre** [comment]
If I see that mac doesn't solve this in their future release, I will add this fix to the main interface. For now, I think the 0 == NaN solution is better (I prefer not manufacture the data by hand, if I can avoid that!)
That is okay for you?
