### ISSUE TITLE
Make install requires sudo (Linux) for copying Python bindings

### ISSUE THREAD

**Issue by mitkof6** [pyomeca/ezc3d#108]
When building the project with Python bindings, it is required to provide sudo privileges so that the Python bindings are copied in /usr/lib for example, even if the CMAKE_INSTALL_PREFIX is set otherwise. It would be best if the Python bindings are copied in the install directory. Then they can be typically installed in a user defined directory manually.

**Comment by pariterre** [comment]
Dear @mitkof6 
Actually, Python cannot be found using CMAKE_INSTALL_PREFIX using the FindPYTHON I have. It actually runs Python and determine which one you used to do so and then refers to that particular one. 

That means if you want to automatically find Python3_EXECUTABLE, you have to load the environment in which you want to use it from. Then it should find it by itself. Otherwise, you have to manually change the Python3_EXECUTABLE variable. In order to help the user, I just made this variable visible in the non-advanced mode, so it is easier to spot (see PR #110). 

I hope this helps!

**Comment by pariterre** [comment]
For the later readers, using `pkgconfig` from conda-forge should also fix the problem

**Comment by mitkof6** [comment]
Hi @pariterre, 

I am coming to this due to the review of pyomeca. I was able to successfully build this project and install it only through sudo on Linux. When I use CMAKE_INSTALL_PREFIX I typically install everything in a non-system directory (e.g., `~/dev/ezc3d/install`). I would like to avoid giving sudo prevelagies when running `make install`. In the current implementation even though things are copied in the CMAKE_INSTALL_PREFIX directory, the python package is copied to `/usr/lib/pythonX.X/site-packages`, making make install fail and requiring sudo. 

An alternative would be to copy this to the user defined package directory of python (e.g., `~/.local/lib/python3.8/site-packages`) or in the CMAKE_INSTALL_PREFIX directory. For example, most people prefer installing python packages (e.g., `pip install xarray --user`) in the user directory not to pollute the system with extra dependencies. On the other hand, if it is copied in the CMAKE_INSTALL_PREFIX/pythonX.X/site-packages/ezc3d directory (example), then the user can navigate there and install the package manually provided there is a setup.py (e.g., python setup.py install --user).

Please let me know if the issue is clarified and the possible alternatives explained. I am raising this, because some people prefer building things on their own and not using conda.

**Comment by pariterre** [comment]
Hi @mitkof6 
Thanks for reaching out! Sorry I wasn't able to answer before, I was out of town.

I see the problem. My CMakeLists.txt is indeed optimized for Conda users, which may be a problem... One thing I could do is to add another install variable (e.g. `PYTHON_INSTALL_PREFIX`) which would take the `PYTHON_SITE_PACKAGE` as default value, but could be override by the user so he can install it anywhere he/she wants? In your case, it would mean to set `PYTHON_INSTALL_PREFIX=~/.local/lib/python3.8/site-packages`. Would that make sense?

**Comment by mitkof6** [comment]
Hi @pariterre ,

Yes, I think this is ok. I can give it a try during the PR.

**Comment by pariterre** [comment]
Hello @mitkof6 !
If you want to give it a quick try, if it answers your concerns, I will merge :)

**Comment by mitkof6** [comment]
@pariterre you can close this. Thanks for addressing this.

**Comment by pariterre** [comment]
Sweet, thx for reporting!
