### ISSUE TITLE
Installing the package installs the python package globally

### ISSUE THREAD

**Issue by chrisdembia** [pyomeca/ezc3d#117]
I think it is good practice to install files *only* into `CMAKE_INSTALL_PREFIX`. Currently, the python package is installed into the system's Python site directory, regardless of `CMAKE_INSTALL_PREFIX`. 

If the user wants this, then they could set `CMAKE_INSTALL_PREFIX` to `/usr/local/`.

**Comment by pariterre** [comment]
Actually it is installed to the Python selected in CMake. So, if you use python from an environment provided by Miniconda (defined in the variable Python3_EXECUTABLE), then it is installed in that particular folder. The problem of not doing this is that the user must add the installation folder to the PYTHON_FOLDER environment variable, and honestly, for what I've seen, it is a complicated extra step for most of the users...

But I definitely understand your point the problem, especially for those who don't use anaconda... 
At least I created an `uninstall` target, so it can be easily removed...

**Comment by pariterre** [comment]
After thinking about it, I still think it makes sense to install things into the folder of selected Python. To help, I improved the CMake finder for Python and therefore should find current Python (and not the system one by default). But if one wants to use its system Python (even though it is probably a bad idea to do so), it seems to me that it makes sense to install ezc3d into the `site-packages` folder of that particular Python (so they don't have to add path to their PYTHON_PATH, which may be tricky...).

Thanks for pointing this out!
