### ISSUE TITLE
Matlab Binder

### ISSUE THREAD

**Issue by zan3566** [pyomeca/ezc3d#122]
Hi,
I downloaded Camke and Visual studio 2017 to install ezc3d.

After I manually type the location of relevant Matlab libraries, Cmake can configure and generate normally.  
![a9200a87447df2e4704eaaef2a42ab8](https://user-images.githubusercontent.com/50066502/81244432-cd58f300-9055-11ea-8d98-5a3783514391.png)
After generating it, I opened  "ezc3d.sln" in visual studio 2017. I click "build" option for "INSTALL" but it failed. I do not know why. Also, I didn't find the variable "MATLAB_ezc3d_INSTALL_DIR" to install the ezc3d to Matlab toolbox.
![e090c3f1d032fc40516d7a14173607b](https://user-images.githubusercontent.com/50066502/81244613-45bfb400-9056-11ea-900f-37869c37fd06.png)

![7cd282062eddd3a8f4ffba2b1b4a958](https://user-images.githubusercontent.com/50066502/81244548-1dd05080-9056-11ea-97b3-e599e2aade2d.png)

Could you help me check it? 
Thank you so much!

**Comment by pariterre** [comment]
Hi @zan3566 !

Usually install fails when Matlab_ezc3d_INSTALL_DIR (or CMAKE_INSTALL_PREFIX) [in CMake] are set to a directory where you need admin rights. Could you show these two keys in CMake?

**Comment by zan3566** [comment]
> Hi @zan3566 !
> 
> Usually install fails when Matlab_ezc3d_INSTALL_DIR (or CMAKE_INSTALL_PREFIX) [in CMake] are set to a directory where you need admin rights. Could you show these two keys in CMake?

Hi @pariterre ,
I changed the folder of CMAKE_INSTALL_PREFIX, and it still failed when I installed it.
![ad8e5ad94d029693f7ce1563908644f](https://user-images.githubusercontent.com/50066502/81252522-7c52fa00-9069-11ea-832c-f7a062d5654b.png)
![b0e0bcc990b75e0dc0b319b707d17ed](https://user-images.githubusercontent.com/50066502/81252528-7e1cbd80-9069-11ea-8dd7-871d624ffefa.png)

**Comment by pariterre** [comment]
Hi again!
CMAKE_INSTALL_PREFIX is one of the two that must be changed (actually, this ones doesn't need to be in Matlab at all). 

The relevant one for Matlab is Matlab_ezc3d_INSTALL_DIR (it may be in the advanced option). I usually put it in My documents/MATLAB

**Comment by zan3566** [comment]
> Hi again!
> CMAKE_INSTALL_PREFIX is one of the two that must be changed (actually, this ones doesn't need to be in Matlab at all).
> 
> The relevant one for Matlab is Matlab_ezc3d_INSTALL_DIR (it may be in the advanced option). I usually put it in My documents/MATLAB

Thank you so much for replying to me!
I have chosen the advanced option, but there is no Matlab_ezc3d_INSTALL_DIR variable.
![f966fe1d7a352c143e63cec18025ea4](https://user-images.githubusercontent.com/50066502/81254023-56c7ef80-906d-11ea-8d39-d762d1fa9349.png)

**Comment by pariterre** [comment]
That is surprising... You said that even though you were giving the MATLAB_ROOT_DIR, it wasn't filling anything be itself? Could you paste me the output of CMake?

**Comment by zan3566** [comment]
> That is surprising... You said that even though you were giving the MATLAB_ROOT_DIR, it wasn't filling anything be itself? Could you paste me the output of CMake?

Sure! The output is below.

[Output.zip](https://github.com/pyomeca/ezc3d/files/4590751/Output.zip)

**Comment by pariterre** [comment]
I meant the message output in the CMake box :sweat_smile:

**Comment by pariterre** [comment]
I install a virtual machine, I'll make some test on Windows to see, if I can reproduce what you are experiencing :)

**Comment by zan3566** [comment]
> I install a virtual machine, I'll make some test on Windows to see, if I can reproduce what you are experiencing :)

Sorry, I misunderstood hah, thank you so much! I really appreciate it!
this is the output of Cmake,
![image](https://user-images.githubusercontent.com/50066502/81305125-4e010900-90c1-11ea-847b-157d17b48cca.png)

**Comment by pariterre** [comment]
This indeed looks like a bug, I still need to install Visual Studio. I come up again when everything is installed!

**Comment by pariterre** [comment]
@zan3566 
This was a false memory I had. On Windows, you must just make sure that CMAKE_INSTALL_PREFIX is somewhere you have rights access.

I just made a video on how to compile and install, please have a look, hopefully this gonna help!

(I'll send you by mail, since I don't know how to import a video in here, please answer here anyway)

**Comment by zan3566** [comment]
Thank you so much! !!

**Comment by pariterre** [comment]
@zan3566 
Have you manage to install everything properly? :)

**Comment by zan3566** [comment]
> @zan3566
> Have you manage to install everything properly? :)

Hi @pariterre ,
Thanks for your replying. Sorry I haven't received the video you made for installing the binder. Could you send it to me?  

you mentioned, "CMAKE_INSTALL_PREFIX is somewhere you have rights access." Does that mean I just need to change the path of it? but I changed it before, it still failed and I showed the picture above. Could you help check it? Hope it will take you so much time.
Thanks!
