### ISSUE TITLE
Error building for Matlab in Win10

### ISSUE THREAD

**Issue by oscampo** [pyomeca/ezc3d#124]
Hi, I'm trying to build ezc3d for matlab in win10. When Building the solution on VS16.0.0 I obtain the following errors:

2>LINK : fatal error LNK1181: cannot open input file 'ezc3d.lib'
2>Done building project "_matlab_Read.vcxproj" -- FAILED.

3>LINK : fatal error LNK1181: cannot open input file 'ezc3d.lib'
3>Done building project "_matlab_Write.vcxproj" -- FAILED.

I searched for that .lib file in my PC and in the web with no results.

**Comment by pariterre** [comment]
Hi @oscampo 
Based on this error message and the fact that you did not find ezc3d.lib file, it feels that you did not built the main project prior to building the MATLAB binder. 

You can have a look at this video I've made for someone else who had problem building the project!
https://www.youtube.com/watch?v=gWno_NXrITA&feature=youtu.be

Please reach back if it does not solve the problem :)

**Comment by oscampo** [comment]
Perfect. Good explanation! Thank you so much!
