### ISSUE TITLE
Wrong results for ID with Opensim and EZC3D

### ISSUE THREAD

**Issue by nikorose87** [pyomeca/ezc3d#143]
Hi @pariterre, how are you?

I am writing to you with the aim of showing some results that ezc3d and Opensim have thrown.

I built Opensim with the last commit of ezc3d you did for the type-3 force platform. I am coding an algorithm to process many c3d files and get the Dynamic Joint Stiffness at different locations (moments and angles). Thus I am establishing a process from scaling to Inverse Dynamics in Opensim.

I am going to show you some results from the GRF using the `C3DFileAdapter`:
![Figure 2020-08-26 224026](https://user-images.githubusercontent.com/14098755/91381790-d250d680-e7ed-11ea-8974-d960fac44ffd.png)
![Figure 2020-08-26 224026 (7)](https://user-images.githubusercontent.com/14098755/91381800-daa91180-e7ed-11ea-8f31-3ec645beb40b.png)
![Figure 2020-08-26 224026 (6)](https://user-images.githubusercontent.com/14098755/91381778-c9f89b80-e7ed-11ea-9662-f334f64ba002.png)

How do you see this behavior? Are the coordinates well established? Is much far the error comparing with other apps?

Another topic are the markers trajectories, which were written using the `TRCfileAdapter`. The following is an example of an ankle angle:

![Figure 2020-08-26 224026 (3)](https://user-images.githubusercontent.com/14098755/91382264-f660e780-e7ee-11ea-966d-7eeeaf780eb0.png)

Previous plots look good for me, but according to the results obtained for moments, I do not know if they really are. The remaining variable was obtained through the `IDtool` but they threw bad results. This is an example of moments in both ankles:

![Figure 2020-08-26 224026 (4)](https://user-images.githubusercontent.com/14098755/91382341-26a88600-e7ef-11ea-9413-c711c0ac3189.png)

As you see is like they were replicating the GRF but is not proportional and obviously, this is not the moment behavior for a sound ankle.

To conclude, I am writing to you with the aim of knowing where the problem could come from, If it might be due to this API or It could be something related to OpenSim.

Thanks. Let me know if I should write to Opensim-core team.

[S01_0004_Gait.zip](https://github.com/pyomeca/ezc3d/files/5133990/S01_0004_Gait.zip)

**Comment by pariterre** [comment]
Hello again!
Sorry for not coming up earlier (I am in vacation since last Sunday up to next Saturday). I have noticed this bug too after my last push. Unfortunately, the fix for this bug greatly affect Opensim reliability. So I must talk to them before moving forward. I asked for an appointment during the next days. 
If they decide not to support Type1 and Type3 force platforms (which I must say may makes sense), I will make a custom fix for you, so you will be able to build and link ezc3d for yourself and have proper results for your C3D. The sad thing is, I won't be able to import it to stable release since the C3D you have are not standard and unusual (for instance, one of them as its vertical axis defined by y instead of z).
Hope this is okay for you!

**Comment by nikorose87** [comment]
OMG, I will appreciate it if you can do this for me. In Latin America there are so many of these platforms, maybe due to they are very old. However, type 3 should be more common and It may be supported. Actually, this data comes from Europe. 

Enjoy your vacations, do not worry too much!
Regards.

PD: I also wrote to Opensim, I will let you know If they answer first.

**Comment by nikorose87** [comment]
I know why the results are wrong, they are presented due to the axis in the C3D file are not properly oriented, I need to swap the Y and Z axis to make it work. I could not do this with OpenSim. I am also swapping from your python wrapping app, however, I do not know which variables should I swap entirely. 

So far, I rotated the data_points, and from data_platform I have rotated `Tz`, `moments`, `force`,` center of pressure` and, `origin`. 

Is anyone missing, is there an automatic function in your API to do so? Should I also modify the `parameters` information?

I am so sorry to bother you so much. I hope you have enjoyed your vacation.

**Comment by nikorose87** [comment]
Hi @pariterre 
Finally, I made it work with the Type 3, all results seem good. Apparently, Opensim does not need to do anything else.

Those are the results for ID, ankle moments specifically.

![Figure 2020-08-26 224026 (10)](https://user-images.githubusercontent.com/14098755/92335128-afc68500-f059-11ea-8481-7e966cc79bc5.png)

Thanks for this. I will be attentive to the type 1, I will also need this :').

**Comment by pariterre** [comment]
Great!
How did you fix it? Did you recreate a new c3d swapping Y and Z?

**Comment by nikorose87** [comment]
I did with ezc3d but did not work, maybe the parameters also need to be changed. I did with Opensim API at the end.

**Comment by pariterre** [comment]
Ok! Good to know, I'll have a look at this :)

**Comment by pariterre** [comment]
@nikorose87 
I could not find ways to differentiate vertical axis being Y or Z. However, I fixed the values when rewriting from non-Intel-float format. Thanks for reporting!
