### ISSUE TITLE
Label2 error

### ISSUE THREAD

**Issue by MSimonlehner** [pyomeca/ezc3d#144]
Dear ezc3d Team,

we have a problem when writing a file.

In our c3d data there is a field c3d['parameters']['POINT']['LABELS2'] when writing, we get the error "'c3d['parameters']['POINT']['LABELS']' must have the same length as nPoints of the data."

c3d['parameters']['POINT']['LABELS'] contains 255 values and in c3d['parameters']['POINT']['LABELS2'] contains 12 values.

The shape of the data array is (4,267,946) values.

Is there a workaround for this problem?

Best regards,
Mark

**Comment by pariterre** [comment]
Wow, i actually did not see this! Sorry about that!
Can you send me the not working file, I'll will patch this I the upcoming days :)

**Comment by MSimonlehner** [comment]
No Problem :)

Thanks for the reply!
I have attached a not working file.

I'm using Python 3.6 with the code:

import ezc3d
c = ezc3d.c3d(pathtofile)
c.write(pathtofile)

The return is: " ValueError: 'c3d['parameters']['POINT']['LABELS']' must have the same length as nPoints of the data."

[Dynamic10.zip](https://github.com/pyomeca/ezc3d/files/5167959/Dynamic10.zip)

**Comment by pariterre** [comment]
Dear @MSimonlehner 
The PR #147 should fix this!
