### ISSUE TITLE
DEC data different after write

### ISSUE THREAD

**Issue by blikpils** [pyomeca/ezc3d#145]
Hey, 

I am struggling getting my (DEC) data to parse. opening is fine and i can see most header info.

The problem is that even without any changes the output data is different: 
![uC3Uc5X](https://user-images.githubusercontent.com/8456656/91861080-68e02600-ec3a-11ea-9ac2-48f59749c5c6.png)
No points are displayed in any of the software packages tested (convert3d and motion builder)

I tried stitching the old header to the new point data but the points are going in all directions.
my assumption is the data gets converted to Intel and some parameters are not transferred over if that is possible?

**Comment by pariterre** [comment]
Oh.. That makes sense.. I'll fix this in the upcomming days!

**Comment by pariterre** [comment]
PR #146 should fix this issue!
@blikpils Thanks for reporting :)

**Comment by blikpils** [comment]
Awesome thank you! Any indication when the build will be available in Anaconda?

**Comment by pariterre** [comment]
@blikpils 
I need to sort something (unrelated) with opensim. But if you need this PR soon, I can make a release as soon as today that includes this part :)

**Comment by pariterre** [comment]
FYI, I just made a release!
Usually, it takes 1 or 2 hours to conda-forge to complete the update, so this should be available by tomorrow 
Enjoy

**Comment by blikpils** [comment]
Hey Thank you for the quick changes, i updated to 1.3.6 this morning and am wondering if there is a parm i should use to keep the data in the same format? Comparing it with the output from 1.3.5 it seems the same and still different from the source material

`import ezc3d
file1 = 'source_files\sourcefile_1.c3d'
f1 = ezc3d.c3d(file1)
f1.write("output.c3d")`

**Comment by pariterre** [comment]
@blikpils 
It definitely won't be the same since I write back all files into the format "Intel float". If you need to write them back into the same formatting (as the original), I would need to change things a bit more...

**Comment by pariterre** [comment]
Small precision, the data though are the same ;)

**Comment by blikpils** [comment]
So i was able to get all the points back after a rebuild of the C3d file, basically loading in the file and assigning the point parameters and some others to a new file. 
No clue why the direct open and save removes the points.
If i find the issue i'll let you know!

Thanks again for the fix!
