### ISSUE TITLE
Python crashing when reading .c3d of Intel processor

### ISSUE THREAD

**Issue by felixbgd** [pyomeca/ezc3d#148]
Hi @pariterre , 

Thank you for this amazing job, I'm writing to you because ezc3d is doing a great job at opening one set of c3d files I have, but fails at opening a lot of others (taking 6 seconds and then Python crashes). I tried to upload 3 files for you to test the problem, in "ezc3d-testFiles", I'm quite new to GitHub so I hope I did it the right way.. They are called "read_working.c3d" or "read_NOTworking1[2].c3d"

I have an intuition about what the problem could be, let me know what's your thought : 

I'm here because the c3d Python Library I use fails at reading c3d files which were formatted in other formats than Intel. (If I'm right, there are 3 formats : DEC, Intel and MIPS). And I have DEC c3d files. And precisely, ezc3d managed to open my DEC files, but not any of the Intel files. Do you know if ezc3d only works for 1 type of processor formatting? 

Thanks in advance, 

Felix

**Comment by pariterre** [comment]
Hi @felixbgd 
I'll have a look! A priori, Intel should be the preferred way for a C3D using ezc3d. 
I let you know as soon as I find something :)

**Comment by felixbgd** [comment]
Thank you for your quick answer! I must add that I just found that the only file working (DEC format) had a fps of 25, instead of the other files (Intel format) which are 250. So it could also be this parameter which causes the problem !

(I installed ezc3d using Anaconda (not compiling myself))

**Comment by pariterre** [comment]
Dear @felixbgd 
I am currently trying to fix the bug. However, I cannot reproduce the bug. The files you provided actually work on my computer. I have recently changed few things in regard with DEC format, so it is not impossible that the current version has already its bug fixed! Could you have a try with the 1.3.6 version? I it still does not work, it means it is OS dependent, I will need the OS you are using so I can reproduce the bug :)

**Comment by felixbgd** [comment]
Dear @pariterre , awesome news, I actually have a new computer on which I re-uploaded the latest version of ezc3d and all the files I shared work ! 

I think the most probable thing is that my new computer has more RAM, or it is that the problem was OS dependent, I'm now working on a Mac OS 10.15.5 :) Anyway, that's awesome, I found a library that enable me to work on my whole dataset, thank you so much ! (I used to import my c3d files using py-c3d)

For your information, half of the mocap corpus I'm working on is published here, it's French Sign Language motion : https://www.ortolang.fr/market/corpora/mocap1/ (it's possible that only BVH files are available, don't hesitate to ask if you're interested in the c3d files! :) )

And if you're interested, I recently published an article about the work we do using these motion files, it's about perceiving identity from mocap : https://dl.acm.org/doi/10.1145/3401956.3404187

Thank you so much for your amazing work !

**Comment by pariterre** [comment]
Good!
Happy this works :)
Bonne journée de Montréal!
