### ISSUE TITLE
Milestones?

### ISSUE THREAD

**Issue by marnunez** [pyomeca/ezc3d#15]
Hi @pariterre! I was just wondering what your plans for ezc3d where. Are you looking for a full replacement of BTK or just a parser? Would you be interested in other more obscure file formats besides c3d? I work in a BTS gaitlab, I could provide some .tdf, .raw, .emg, .ric, files, among others.

**Comment by pariterre** [comment]
Hello @marnunez, 

For the future development, I'd say that it highly depends on the needs of the community. Up to now, my goal was to parse and write c3d into c++, matlab and python for the lab where I work. This goal is now achieved as ezc3d is now the parser/writer that we use at the lab.

Hence, now I am moving to the community needs. That is why I came to OpenSim as you have seen. Their needs and those from whomever may be interested in the project will drive its future development. To answer you question more specifically though, for what I've seen, BTK was actually quite a big project and in the short term I just won't have the time to fully replace it. So I'd not say a full replacement but as most as possible in humanly possible time!

I would definitely be interested in more c3d files! I opened another repo to put them if you want to contribute. For the other format, for now, I will keep ezc3d into c3d files (it is mostly a matter of time). But I definitely may consider a ToC3D in a mid-term future :)
