### ISSUE TITLE
TypeError: 'c3d' object is not subscriptable

### ISSUE THREAD

**Issue by AnkurAgrawal** [pyomeca/ezc3d#150]
Hi @pariterre,

I compiled the library with **python** bindings using python v3.8. While trying to use it though, I am getting an error:

```python
import ezc3d

# Load an empty c3d structure
c = ezc3d.c3d()
c.console_print()

# Fill it with random data
c["parameters"]["POINT"]["RATE"]["value"] = [100]
```

Error:
```
TypeError: 'c3d' object is not subscriptable
```

I compiled and tried it on both macOS (statically linked) and Linux (dynamically linked) platforms and received the same error. I am attaching the compiled libraries for macOS in case it's helpful. [ezc3d.zip](https://github.com/pyomeca/ezc3d/files/5235110/ezc3d.zip)

I followed the following steps to compile ezc3d libs:
```bash
git clone https://github.com/pyomeca/ezc3d.git

cd ezc3d && mkdir build && cd build

cmake ../ -DBUILD_SHARED_LIBS=FALSE -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLE=FALSE -DBINDER_PYTHON3=ON -DPython3_EXECUTABLE=<path to python binary> -DSWIG_EXECUTABLE=<path to swig root>/swig -DSWIG_DIR=<path to swig root>/Lib

make -j $(nproc)
```

Thank you,
Ankur

**Comment by pariterre** [comment]
Hi @AnkurAgrawal 

Thanks for trying ezc3d :)
Based on the zip file you provided and the command line you showed, it seems that you did not `make install` the library. It seems that you therefore missed one important Python file (__init__.py) 
Could you have a try using make install ?

**Comment by AnkurAgrawal** [comment]
Thanks for your reply @pariterre. You're correct, I didn't do `make install`. As I understand it, `make install` just copies the library files to a target location. So, instead of doing that, I copied the files manually from "ezc3d/build/binding/python3" to a local folder of a project. I want to keep the library local to the project so that I can move the project to a different machine (with the same platform) without needing to run through the installation process again.

Thank you for pointing me to the right direction, though. I found the **\_init\_.py** file in "ezc3d/binding/python3" which defines the c3d wrapper on top of swig's c3d class. I copied this file alongside the ezc3d.py and _ezc3d.so and all is well now. I wrongly assumed that all the files needed for the library will be copied to the "ezc3d/build/binding/python3" folder as part of the build process.

Please go ahead and close this issue.
