### ISSUE TITLE
Add integration to 📦 VCPKG

### ISSUE THREAD

**Issue by RDCH106** [pyomeca/ezc3d#161]
Add port for [VCPKG](https://github.com/microsoft/vcpkg) package management tool.

Current PR waiting for integration: https://github.com/microsoft/vcpkg/pull/14016

⚠️ If PR is accepted, the README must be updated

**Comment by RDCH106** [comment]
ezc3d was included in VCPKG: https://github.com/microsoft/vcpkg/pull/14016#pullrequestreview-511374568

🎉🎉🎉

And it will be available for the next release.

**Comment by RDCH106** [comment]
⚠️⏳ Keep open this issue until the usage of the ezc3d library with VCPKG will be documented in README

**Comment by pariterre** [comment]
Hello!
Sorry, for some reasons I completely missed this! What exactly is VCPKG? That is awesome work you did! Thanks for contributing :)

**Comment by RDCH106** [comment]
[VCPKG](https://docs.microsoft.com/en-US/cpp/build/vcpkg) is a package manager powered by Microsoft for C++ libraries. It will improve the usability and distribution of the ezc3d library. ezc3d is prepared by vpkg using the release tags of this repository.

I will generate the specific documentation in the README in a PR when the next release of [vcpkg](https://github.com/microsoft/vcpkg) is ready.

**Comment by pariterre** [comment]
Dear @RDCH106 
Should I keep this issue open?

**Comment by RDCH106** [comment]
> 
> 
> Dear @RDCH106
> Should I keep this issue open?

Yes, I am going to generate the specific documentation use ezc3d using vcpkg. Keep the issue open and I will close it with the PR.

Thanks in advance
