### ISSUE TITLE
Install ezc3d in Google CoLab

### ISSUE THREAD

**Issue by andyzhao1** [pyomeca/ezc3d#168]
Hi all, 

Recently, I want to install ezc3d in Google CoLab using this command: conda install -c conda-forge ezc3d

This command can work well, but when I import ezc3d, it raised an ImportError:
ImportError: /usr/local/lib/python3.7/site-packages/ezc3d/_ezc3d.so: undefined symbol: _ZN5ezc3d3c3d5pointERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE

Anyone can help me to solve this?

Thanks in advance!

**Comment by pariterre** [comment]
Hello @andyzhao1 !
Are you using hosted or local python?

**Comment by pariterre** [comment]
Hello again!
I tried using a hosted environment. When installing conda (and ezc3d using conda), and then adding the install directory to the sys.path, it works just fine:
```bash
%%bash
MINICONDA_INSTALLER_SCRIPT=Miniconda3-latest-Linux-x86_64.sh
MINICONDA_PREFIX=/usr/local
wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
chmod +x $MINICONDA_INSTALLER_SCRIPT
./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

conda install ezc3d -cconda-forge -y
```
```python
import sys
_ = sys.path.append("/usr/local/lib/python3.8/site-packages")
```
After running these two cells, this cell works as expected:
```python
import ezc3d
c3d = ezc3d.c3d()
print(c3d["parameters"].keys())
```

**Comment by andyzhao1** [comment]
It works, thank you for your help!
