### ISSUE TITLE
install ezc3d in Google CoLab

### ISSUE THREAD

**Issue by andyzhao1** [pyomeca/ezc3d#169]
Hi again,

I asked a question about installing ezc3d in Google CoLab a couple of days ago, and I have got a solution which asked me to use the latest version of miniconda and set the sys.path. That solution works well.

However, because I have to use some packages which only be supported by python 3.7, I cannot use the latest version of miniconda. When I switch the conda to python 3.7, ezc3d raise the error again:
ImportError: /usr/local/lib/python3.7/site-packages/ezc3d/_ezc3d.so: undefined symbol: _ZN5ezc3d3c3d5pointERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE

Does it mean ezc3d is not supported by older version of python? I'm using Google Colab on the host.

Thanks!

**Comment by pariterre** [comment]
Hi there,

Miniconda is not attached to a specific version of Python. You can install python 3.7 in an environment from the newest miniconda.
To install both python 3.7 and ezc3d at the same time you can chain them, but installing them one after the other is just fine too.
```bash
conda install python=3.7 ezc3d -cconda-forge
```
See ya

**Comment by andyzhao1** [comment]
Yes, I do install the newest miniconda and select python 3.7 to install ezc3d and other packages. Packages can be installed well, however, only ezc3d raised Import error. When I used python 3.8, it works fine. (ezc3d works fine with Python 3.7 several months ago when I first used it, but it raised this error now. It just happened recently.)

So I guess if ezc3d is no longer supported by Python 3.7？

**Comment by pariterre** [comment]
In Google Colab, this code actually works for me...
```bash
%%bash
MINICONDA_INSTALLER_SCRIPT=Miniconda3-latest-Linux-x86_64.sh
MINICONDA_PREFIX=/usr/local
wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
chmod +x $MINICONDA_INSTALLER_SCRIPT
./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

conda install python=3.7 ezc3d -cconda-forge -y
```
```python
import sys
_ = sys.path.append("/usr/local/lib/python3.7/site-packages")
```
```python
import ezc3d
c3d = ezc3d.c3d()
print(c3d["parameters"].keys())
```

**Comment by andyzhao1** [comment]
Sorry, I'm new for Google Colab, maybe I did something wrong. When I run your code, it works for me. But when I merged them into one cell, it raises import error...

Anyway, the problem is solved, thank you for your help and patient!
