### ISSUE TITLE
Problem with force data

### ISSUE THREAD

**Issue by mrrezaie** [pyomeca/ezc3d#174]
Hi,

Happy new year!

I was trying to learn how to use EZC3D and I faced this issue:
The C3D file I used has 3 force plates and I extract the values like this:

```
c = c3d('example.c3d', extract_forceplat_data=True)
n = c['parameters']['FORCE_PLATFORM']['USED']['value'][0]
a = list()
for i in range(0,n):
    a.append(c["data"]["platform"][i]['force'])

b = np.array(a)
plt.plot(b[0,2,:])
plt.plot(b[1,2,:])
plt.plot(b[2,2,:])
```
and this is the results:

![image](https://user-images.githubusercontent.com/38867713/103835650-1907e480-509c-11eb-8783-fca2ec73fec7.png)

While it must be like this (from MOKKA):

![image](https://user-images.githubusercontent.com/38867713/103835774-61bf9d80-509c-11eb-97a3-9902aa2e2e3a.png)

Did I forget something like calibration after extraction of the force data?

There is no rush, so enjoy your holidays.

Your help is much appreciated.

Cheers,
Mohammadreza

**Comment by pariterre** [comment]
Dear @kernalnet 

It seems there that OFFSET is not applied when extracting the results from the force platform. Since it is the first time I face a platform with an OFFSET, I did not implemented it!

If you want a quick fix, I suggest that you find the OFFSET value in parameters or to use the first frame to subtract the data. In any case, if you can provide me with the C3D, I will properly fix this for the next release!

**Comment by mrrezaie** [comment]
Thank you so much for your response.

You're right, I see the analog offset in the metadata.

I selected this C3D file just for test. It belongs to the GaitExtractToolbox171.
[example.zip](https://github.com/pyomeca/ezc3d/files/5779212/example.zip)

**Comment by pariterre** [comment]
@mrrezaie 
I there! I think I found the problem. For some reason, the OFFSET in you file is negative... so when I subtract it, it actually adds it... I added an absolute and it seems to solve the problem
![image](https://user-images.githubusercontent.com/17518525/103928253-93ab2100-50e9-11eb-90cd-edfe563e5710.png)

When I accept this PR #175 I'll make the 1.3.9 release so you can download from conda-forge

Regards
