### ISSUE TITLE
[JOSS review] MATLAB examples are bugged

### ISSUE THREAD

**Issue by modenaxe** [pyomeca/ezc3d#181]
All MATLAB examples have a misspell I think : `parameter` should be `parameters`, in order for work. 

Take the first one:

```
c3d = ezc3dRead();
disp(c3d.parameter.POINT.USED); % Print the number of points used
```
only works as:
```
c3d = ezc3dRead();
disp(c3d.parameters.POINT.USED); % Print the number of points used
```

As part of the JOSS review, can you please fix the examples?

**Comment by pariterre** [comment]
That is correct, as point in #182, the examples dates from a previous version and I forgot to update them, they actually should read: 
```MATLAB
c3d = ezc3dRead();
disp(c3d.parameters.POINT.USED.DATA); % Print the number of points used
```
All the examples in the ReadMe were updated, sorry about that

**Comment by modenaxe** [comment]
thank you, now it works!
