### ISSUE TITLE
[JOSS review] MATLAB bug when writing c3d

### ISSUE THREAD

**Issue by modenaxe** [pyomeca/ezc3d#182]
The [write a c3d section](https://github.com/pyomeca/ezc3d#write-a-c3d-1) throws an error, as if the frame rate was not specified. 
```
Unexpected Standard exception from MEX file.
What() is:Point frame rate must be specified if you add some
..

Error in test_ez (line 24)
ezc3dWrite('test.c3d', c3d);
```
The error in the C++ code should be thrown is the frame rate is zero, but here it is defined. I have tried defining RATE explicitly as type double in MATLAB but that didn't help.

**Comment by pariterre** [comment]
I am sorry, the ReadMe was completely out of date...
The section you refer to should have read:
```MATLAB
% Create a valid structure to work on
c3d = ezc3dRead();

% Add a point to the structure. 
c3d.parameters.POINT.RATE.DATA = 100;
c3d.parameters.POINT.USED.DATA = c3d.parameters.POINT.USED.DATA + 1;
c3d.parameters.POINT.LABELS.DATA = [c3d.parameters.POINT.LABELS.DATA, 'NewMarkerName'];
c3d.data.points = rand(3,1,100);

% Write the C3D
ezc3dWrite('path_to_c3d.c3d', c3d);
```

The ReadMe is now up-to-date with the 1.3.x API

**Comment by modenaxe** [comment]
this is also working, thank you.
