### ISSUE TITLE
[JOSS review] guidelines for contribution

### ISSUE THREAD

**Issue by modenaxe** [pyomeca/ezc3d#185]
based on the JOSS review questions it seems that the README is missing clear indications on how to:
- [ ] Report issues or problems with the software 
- [ ] Seek support

**Comment by pariterre** [comment]
I am not sure what these sections should be filled with. I changed the name of the section `troubleshoots` for `Support` which I expanded with a subsection `Report issues`.
I did not find on the JOSS website more explanation on how the two sections you mentioned should appear... If what I have done so far is not enough, could you provide me with the link that you refer?

Thanks for your review!

**Comment by modenaxe** [comment]
Honestly the guidelines have changed since the last time I reviewed for JOSS. I think it's enough if you point to the Issue section with a link in case someone finds a bug
