### ISSUE TITLE
octave_install

### ISSUE THREAD

**Issue by pauk98** [pyomeca/ezc3d#191]
hi, i'm triying to install the ezc3d to use it in octave, but it's not working. (windows 10, 64bit, cmake 2.19.6, octave 5.2.0).
1.)i've downloaded the ezc3d code from this website
2.)in cmake: "where is the source code": ....C:.../ezc3d-dev;"where to build the binaries": C:/...ezc3d-dev/build-octave
3.)congigure:
first thing i tried: with "MinGW Makefiles -- use default native compilers" --> configuration, generation and installation worked, but there are no functions in the folder, that i can open with octave (to read/write the c3dfile).
so i tried the same with selecting the Binder_Matlab, but it is not working because of an error in the configuration process
(i also tried to specify native compilers from my octave file= g++,gcc, gfortran, but there is also an error in the configuration process, where a .dll file is not found)

am i right, that i have to select the matlab binder, so it builts the code for the functions?
what chances do i have to make (in the cmakelists) so i can run the code with octave?

i would be very happy, if you can help me

**Comment by pariterre** [comment]
Hi @pauk98 

I have never compiled for octave... A priori, there is no inherent problem to do so. 
In my opinion, you are correct to select the Binder_Matlab option. However, cmake will probably fail at configuration because it is designed to find the Matlab root folder when Binder_Matlab is ON. When it does not find it, it simply crashes (because of the REQUIRED option in the CMakeLists). 
If you have any experience with CMake, the easy fix is to slightly change the CMakeLists.txt in Binder_Matlab to find octave instead of Matlab, and adjust the linker and include accordingly. If you do not have any experience, it may be a bit hard... I could have a look this week if I can add support for octave!

**Comment by pauk98** [comment]
hi, thanks for your quick reply. to be honest, i do not really have expierence with cmake. i've tried to change the cmakelists a little, but i get this error and can't solve it, with my little knowledge:

CMake Error at binding/matlab/CMakeLists.txt:4 (find_package):
  By not providing "FindOctave.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Octave", but
  CMake did not find one.

  Could not find a package configuration file provided by "Octave" with any
  of the following names:

    OctaveConfig.cmake
    octave-config.cmake

  Add the installation prefix of "Octave" to CMAKE_PREFIX_PATH or set
  "Octave_DIR" to a directory containing one of the above files.  If "Octave"
  provides a separate development package or SDK, be sure it has been
  installed.

it would be great, if you can tell me, what exactly i have to change, or if you can have a look at it. thanks

**Comment by pariterre** [comment]
You should now see an "Octave_DIR" option in the CMake output (in the GUI), you have to set this variable to the root folder of Octave installation directory. Then, it should find the Libraries and Include_dir by itself.

**Comment by pauk98** [comment]
Yes, I can see the "Octave_Dir" option in Cmake. I've tried some folders, but the error is every time the same. Do you know, which one is the root folder (the name/path)?

**Comment by pariterre** [comment]
I don't know which one is the right one. Make sure you have the SDK version installed (if you already compiled in the past, you have a SDK version).

I can have a look during the week if I have time!

**Comment by pauk98** [comment]
it's the first time for me to compile, so now i've downloaded SDK. it's still not working, do i have to put SDK to octave?

**Comment by pariterre** [comment]
I honestly have no clue, I have never used octave before (let alone compiling). But I would enjoy having an octave version of ezc3d. I am pretty busy this week, but I'll try to find some time.. If I did not come back to you in a week, please ping me back, I may have forgotten!

**Comment by pauk98** [comment]
ok, thanks.

**Comment by pariterre** [comment]
Hi @pauk98 
I added a branch octave_support in my personal repository, which allows to compile for octave on Linux when octave was compiled from Linux. Could you have a try on Windows? I don't have much hope right now (I will try it myself soon, but who knows, maybe it works already!)

**Comment by pauk98** [comment]
Hi @pariterre , unfortunately it's not working. it says: configuration and generation done, but the value for 'Octave_Config_Executable' was not found and the 'octave_ezc3d_install_dir' only has the value '/toolbox'.
I manually set the 'config_execuatable' to 'C:\Program Files\Octave-6.2.0'. and tried some for the 'octave_ezc3d_install_dir', here i got this output from cmake:

Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
C:/Users/paulk/Desktop/ezc3d-octave_support/binding/octave/OCTAVE_INCLUDE_DIRS
   used as include directory in directory C:/Users/paulk/Desktop/ezc3d-octave_support/binding/octave
   used as include directory in directory C:/Users/paulk/Desktop/ezc3d-octave_support/binding/octave

Generating done

I tried to install it, but windows cmd gave me this:

C:\Users\paulk\Desktop\ezc3d-octave_support\build-octave>mingw32-make
[ 61%] Built target ezc3d
Scanning dependencies of target ezc3d_octave_Read
[ 64%] Building CXX object binding/octave/CMakeFiles/ezc3d_octave_Read.dir/utils.cpp.obj
C:\Users\paulk\Desktop\ezc3d-octave_support\binding\octave\utils.cpp:1:17: fatal error: mex.h: No such file or directory
 #include "mex.h"
                 ^
compilation terminated.
binding\octave\CMakeFiles\ezc3d_octave_Read.dir\build.make:81: recipe for target 'binding/octave/CMakeFiles/ezc3d_octave_Read.dir/utils.cpp.obj' failed
mingw32-make[2]: *** [binding/octave/CMakeFiles/ezc3d_octave_Read.dir/utils.cpp.obj] Error 1
CMakeFiles\Makefile2:213: recipe for target 'binding/octave/CMakeFiles/ezc3d_octave_Read.dir/all' failed
mingw32-make[1]: *** [binding/octave/CMakeFiles/ezc3d_octave_Read.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

I don't know how to fix it...

**Comment by pariterre** [comment]
Don't worry, that is what I was expecting 
It should not be much complicated to fix :)
I'll give it a try today, I have a virtual box with Windows that I can use
I'll keep you posted!

**Comment by pariterre** [comment]
Hi @pauk98 !
I think it should work now (from my branch) :)
If you can have a try, once you confirm, I will accept the PR #192  so Octave is officially supported.

**Comment by pauk98** [comment]
Hi @pariterre it's not working on my computer. configuration and generation is complete, after I manually set 'OCTAVE_ROOT_DIR' to 'C:/Program Files/Octave-6.2.0'. But this is my output when trying to install in 'cmd':

C:\Users\paulk\Desktop\ezc3d-octave_support\binding\octave>cd C:\Users\paulk\Desktop\ezc3d-octave_support\build-octave

C:\Users\paulk\Desktop\ezc3d-octave_support\build-octave>mingw32-make
Scanning dependencies of target ezc3d
[  3%] Building CXX object CMakeFiles/ezc3d.dir/src/math/Matrix.cpp.obj
[  6%] Building CXX object CMakeFiles/ezc3d.dir/src/math/Matrix33.cpp.obj
[  9%] Building CXX object CMakeFiles/ezc3d.dir/src/math/Matrix66.cpp.obj
[ 12%] Building CXX object CMakeFiles/ezc3d.dir/src/math/Vector3d.cpp.obj
[ 16%] Building CXX object CMakeFiles/ezc3d.dir/src/math/Vector6d.cpp.obj
[ 19%] Building CXX object CMakeFiles/ezc3d.dir/src/Analogs.cpp.obj
[ 22%] Building CXX object CMakeFiles/ezc3d.dir/src/Channel.cpp.obj
[ 25%] Building CXX object CMakeFiles/ezc3d.dir/src/Data.cpp.obj
[ 29%] Building CXX object CMakeFiles/ezc3d.dir/src/ezc3d.cpp.obj
[ 32%] Building CXX object CMakeFiles/ezc3d.dir/src/Frame.cpp.obj
[ 35%] Building CXX object CMakeFiles/ezc3d.dir/src/Group.cpp.obj
[ 38%] Building CXX object CMakeFiles/ezc3d.dir/src/Header.cpp.obj
[ 41%] Building CXX object CMakeFiles/ezc3d.dir/src/Parameter.cpp.obj
[ 45%] Building CXX object CMakeFiles/ezc3d.dir/src/Parameters.cpp.obj
[ 48%] Building CXX object CMakeFiles/ezc3d.dir/src/Point.cpp.obj
[ 51%] Building CXX object CMakeFiles/ezc3d.dir/src/Points.cpp.obj
[ 54%] Building CXX object CMakeFiles/ezc3d.dir/src/Subframe.cpp.obj
[ 58%] Building CXX object CMakeFiles/ezc3d.dir/src/modules/ForcePlatforms.cpp.obj
[ 61%] Linking CXX shared library libezc3d.dll
[ 61%] Built target ezc3d
Scanning dependencies of target ezc3d_octave_Read
[ 64%] Building CXX object binding/octave/CMakeFiles/ezc3d_octave_Read.dir/utils.cpp.obj
C:\Users\paulk\Desktop\ezc3d-octave_support\binding\octave\utils.cpp:1:17: fatal error: mex.h: No such file or directory
 #include "mex.h"
                 ^
compilation terminated.
binding\octave\CMakeFiles\ezc3d_octave_Read.dir\build.make:81: recipe for target 'binding/octave/CMakeFiles/ezc3d_octave_Read.dir/utils.cpp.obj' failed
mingw32-make[2]: *** [binding/octave/CMakeFiles/ezc3d_octave_Read.dir/utils.cpp.obj] Error 1
CMakeFiles\Makefile2:213: recipe for target 'binding/octave/CMakeFiles/ezc3d_octave_Read.dir/all' failed
mingw32-make[1]: *** [binding/octave/CMakeFiles/ezc3d_octave_Read.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
mingw32-make: *** [all] Error 2


For compyling in Cmake I used 'MinGW Makefiles' -->'use default native compilers'

Don't know whats wrong. You have an idea, or do you think I have to change or install something on my computer so it works also for me?

**Comment by pauk98** [comment]
At another try, that was the error:

C:\Users\paulk\Desktop\ezc3d-octave_support\build-octave>mingw32-make
[ 61%] Built target ezc3d
[ 64%] Building CXX object binding/octave/CMakeFiles/ezc3d_octave_Read.dir/ezc3dRead.cpp.obj
C:\Users\paulk\Desktop\ezc3d-octave_support\binding\octave\ezc3dRead.cpp:9:117: fatal error: ../../ezc3d/include/Data.h: No such file or directory
 #include "../../ezc3d/include/Data.h"  // This clash with data.h from Octave.. It will fail if directories are moved
                                                                                                                     ^
compilation terminated.
binding\octave\CMakeFiles\ezc3d_octave_Read.dir\build.make:95: recipe for target 'binding/octave/CMakeFiles/ezc3d_octave_Read.dir/ezc3dRead.cpp.obj' failed
mingw32-make[2]: *** [binding/octave/CMakeFiles/ezc3d_octave_Read.dir/ezc3dRead.cpp.obj] Error 1
CMakeFiles\Makefile2:213: recipe for target 'binding/octave/CMakeFiles/ezc3d_octave_Read.dir/all' failed
mingw32-make[1]: *** [binding/octave/CMakeFiles/ezc3d_octave_Read.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by pariterre** [comment]
Ok! it seems we almost got there!
Data.h has an unfortunate clash with data.h from Octave. 

Could you try to replace this line by an absolute path (replace the "../../ezc3d" by the ezc3d root folder so this is an absolute path to the Data.h file). If this compiles, I think I'll simply change the Data.h file name haha

**Comment by pauk98** [comment]
[error.txt](https://github.com/pyomeca/ezc3d/files/6193082/error.txt)

ok, i changed the path to the absolute path (#include "C:\Users\paulk\Desktop\ezc3d-octave_support\ezc3d-octave_support\include\Data.h") in the file C:\Users\paulk\Desktop\ezc3d-octave_support\ezc3d-octave_support\binding\octave\ezc3dRead

error is in the txt file

**Comment by pariterre** [comment]
Ok cool, so this works! What have you done to make the mex.h works?

Now, the only remaining problem is the linker. It seems that CMake did not find `liboctinterp.dll.a`. Can you locate this file in the installation folder and tell me where it is?

**Comment by pauk98** [comment]
file is located in 'C:\Program Files\Octave-6.2.0\mingw64\lib\octave\6.2.0'

I changed the path of 'octave_ezc3d_install_dir' to 'C:/Program Files/Octave-6.2.0/mingw64/share/octave/packages'

**Comment by pariterre** [comment]
> I changed the path of 'octave_ezc3d_install_dir' to 'C:/Program Files/Octave-6.2.0/mingw64/share/octave/packages'

That is okay, It should not cause any problem

> C:\Program Files\Octave-6.2.0\mingw64\lib\octave\6.2.0

That seems what I expected... Can you add this line in the file `ezc3d/modules/FindOctave.cmake` at line 158:
`message(${OCTAVE_LIBRARIES_PATHS})` 
And paste me the output of CMake when you configure. 

I'll continue to interact tomorrow, I am hosting a live podcast in less than an hour and I need to focus on this now :)

**Comment by pauk98** [comment]
C:\Program Files\Octave-6.2.0\mingw64\lib\octave\6.2.0
Configuring done
Generating done

(first line in red)

[CMakeOutput.log](https://github.com/pyomeca/ezc3d/files/6193227/CMakeOutput.log)
here's also the complete output

ok :)

**Comment by pariterre** [comment]
Hi @pauk98 
Just to keep you posted. I could reproduced your bug. It is because of mingw, for some reason it does not seem to link, the exact same CMake works just fine with Visual Studio. Since I have never compiled with mingw before, I'll have to look why the linking process fails. Apart from that, everything seems fine

**Comment by pariterre** [comment]
What I suspect if that `libcruft.dll.a` is necessary when compiling using mingw, but is not when compiling using VS. The dll itself is probably loaded by octave when it runs. Unfortunately for some reason octave is not delivered with the cruft option on... I could not find an easy way to compile octave myself though... I may have another try next week.

My suggestion: if you compiled yourself octave, try to compile it so it creates the libcruft.dll.a file next to the other dll file. If you achieve that, I'll push something on the branch so you can test ezc3d. Otherwise, I would suggest to use VS2019 community

Sorry for that :(

**Comment by pauk98** [comment]
hi @pariterre 
I tried to use VS2019 community (my first time...), and it's not working :( sorry...

In cmake I use VS2019 as compiler (1x with default compilers; 1x with specified compilers from octave), set the Cmake_configuration_types (1x release; 1x debug). I set the ROOT value to the octave path and the PREFIX to the octave packages. 

configuration and generation works, next, I open the Project in VS19 and after Debugging I get the Error: the programme 'C:\Users\paulk\Desktop\ezc3d\ezc3d-octave_support\build-octave\x64\Debug\ALL_BUILD' cannot be started -- access denied

Do you know this problem?

**Comment by pariterre** [comment]
It seems to be related to access limitation, as if you were required to have administrator rights to build-octave (and further) folder..
The variable that you are supposed to set are CMAKE_INSTALL_PREFIX to a folder that you have rights to write, and Octave_ezc3d_INSTALL_DIR (where you must have access too).
But it does not seems to be the problem here... 

When you restarted the process, did you completely removed the build folder? Sometimes when we try to reuse this folder, it creates issues..

**Comment by pauk98** [comment]
I don't know whats wrong, now I've tried several times with different folders, where I had all rights.... I also completely removed the build folder.

**Comment by pariterre** [comment]
Hi there!
Could you confirm that what you are doing resemble this: https://cloud.pariterre.net/index.php/s/nKLyf9PfK7cob4M

**Comment by pauk98** [comment]
Hi @pariterre, thanks to you, it's working now :)
What I was doing wasn't exactly the same, but now I tried it copletely equal and thats it. (I think maybe, I did some wrong steps in VS2019 bevore). 
Thank you for helping me, and sorry for me beeing incompetent :)

**Comment by pariterre** [comment]
Happy days!
Enjoy!

**Comment by pariterre** [comment]
Hi @pauk98 
Just so you know, the octave binder is now part of the main branch #192 :)
Thanks for push me on this!
