### ISSUE TITLE
COP

### ISSUE THREAD

**Issue by mrrezaie** [pyomeca/ezc3d#193]
Hi Pariterre,

Hope you are well and Thank you for your efforts.

I'm curious to know whether the center of pressure data extracted from ezc3d is Point Of Wrench (like BTK) or it is calculated based on formulas for each specific force platform type. 

Your help is much appreciated.

Regards,
Mohammadreza

**Comment by pariterre** [comment]
Hi @mrrezaie !
For most of the force plateform, the center of pressure is not stored in the c3d file. It is therefore computed. Conversely, when CoP is given, it is the Moment which is computed. In all case, the c3d format never provides redundant information (at least in the standardized form) 
So depending on how the force platform is stored (TYPE of force platform), CoP may or may not be computed

I hope it answers your question!

**Comment by mrrezaie** [comment]
Thanks for your response.

Have a great time.
