### ISSUE TITLE
Special Member Functions

### ISSUE THREAD

**Issue by Kilidsch** [pyomeca/ezc3d#202]
**Problem:**

The `ezc3d::c3d`-class does use compiler generated special member functions (i.e. copy/move-constructor, copy/move-assignment). This results in double-free's when using these, since only the pointers, not the memory they're pointing to are copied/moved.

**Repoduction:**

```cpp
    { // outer scope, so "moved-to" c3d-object also goes out of scope for second free; same happens with copy
        ezc3d::c3d c3d;
        try{
            c3d = std::move(ezc3d::c3d(R"(C:\Path\To\File\sample.c3d)"));
        }catch(std::exception& e){
            std::cerr << "Exception occured during reading of c3d-file " << e.what() << "\n";
        }
    }
```

**Resolution:**

There are 2 ways of dealing with this.
1. Explicitly delete these special member functions (seems more restrictive than needed)
2. Implement them correctly

I personally would prefer the second option (I found this error when using the special member function, so there is a usecase).

**Comment by pariterre** [comment]
Hi @Kilidsch !
Thanks for reporting. I changed the nature of the char* to vector<char> and removed the destructor. This seems to work just fine and does not seem to have any performance issue. 
Therefore, unless I misinterpreted the issue, this is now solve in #203 
Cheers!

**Comment by Kilidsch** [comment]
Hi @pariterre 
Thank you very much for the fast reply and solution!

This indeed solved my issue. Just one minor thing

The copy assignment/constructor seems to do shallow copies, since you're using `shared_ptr`, i.e. if you change the header of a c3d-object you change the header of the copy as well. This should probably be documented.

Depending on if you think such a shallow copy is useful or not, you could also delete the copy-functions so the object can only be moved, i.e.

```cpp
c3d(const c3d&) = delete;
c3d(c3d&&) = default;
c3d& operator=(const c3d&) = delete;
c3d& operator=(c3d&&) = default;
virtual ~c3d() = default;
```

Thanks again!

**Comment by pariterre** [comment]
Hi @Kilidsch 
I think the shared_ptr (that creates the shallow copy) actually makes sense for the speed of the code. I will definitely add your piece of code then! 

Thanks for the tip :)

**Comment by pariterre** [comment]
This is now added in the doc #205 
Thanks for reporting :)
