### ISSUE TITLE
adding "events" on a newc3d

### ISSUE THREAD

**Issue by ErDelhaye** [pyomeca/ezc3d#204]
Hello everyone, 

Thank you for the development of ezc3d ! That's great ! 

I have developped my own routines to process trajectories from c3d on python. 
I would like to identify on signals some events and then write them in the c3d (and write a new one).

I found out how to add events_labels and events_time, but, when writing the c3d, events are empty. 
Am I doing something wrong? I didn't see anything in the sourcecode, related to the recording of events during post-process?

Thank you for your answer !

**Comment by pariterre** [comment]
Hi @ErDelhaye 
I have never worked so far with the events. So I am not sure if they even are implemented in ezc3d! That said, if you provide me with a c3d that has events in it, I could implemented them for the Python and Matlab interface :)

**Comment by ErDelhaye** [comment]
> Hi @ErDelhaye
> I have never worked so far with the events. So I am not sure if they even are implemented in ezc3d! That said, if you provide me with a c3d that has events in it, I could implemented them for the Python and Matlab interface :)

Hi @pariterre , thanks for your (quick) answer.
Actually, they seem to be implemented in ezc3d. I mean, I can add new events in a c3d object :

newC3D['header']["events"]["size"] = len(events_labels)
newC3D['header']["events"]["events_time"] = tuple(events_time)
newC3D['header']["events"]["events_label"] = tuple(events_labels)

 The only problem is when I want to save the c3d, It doesn't save the events I previously add in.

I work in swimming, and, from trajectories, I identify intracyclic events, that I would like to add in a c3d, and then save it. So I currently don't have any c3d with events already saved in it, I'm sorry :/

**Comment by marnunez** [comment]
Hi! This is how I add events from a BTS MDX file to a c3d. It's not pretty, but might be of use. Tested it with Mokka:

``` python 
   def load_events(self):
        # Loading events from the mdx
        events = self.mdx.trial.static.events
        eRHS = events["eRHS"].data
        eLHS = events["eLHS"].data
        eRTO = events["eRTO"].data
        eLTO = events["eLTO"].data

        event_length = len(eRHS) + len(eRTO) + len(eLHS) + len(eLTO)
        event_contexts = (
            ["Right"] * len(eRHS)
            + ["Right"] * len(eRTO)
            + ["Left"] * len(eLHS)
            + ["Left"] * len(eLTO)
        )
        event_labels = (
            ["Foot Strike"] * len(eRHS)
            + ["Foot Off"] * len(eRTO)
            + ["Foot Strike"] * len(eLHS)
            + ["Foot Off"] * len(eLTO)
        )
        event_descriptions = [""] * event_length
        event_iconsid = (
            [1] * len(eRHS) + [2] * len(eRTO) + [1] * len(eLHS) + [2] * len(eLTO)
        )
        event_times = eRHS + eRTO + eLHS + eLTO
        event_times = np.array(
            [j for i in zip(list([0] * event_length), event_times) for j in i]
        )

        self.c3d["parameters"]._storage["EVENT"] = {
            "__METADATA__": {"DESCRIPTION": "Events", "IS_LOCKED": False},
            "USED": {
                "type": 2,
                "description": "Total amount of events",
                "is_locked": False,
                "value": [event_length],
            },
            "CONTEXTS": {
                "type": -1,
                "description": "",
                "is_locked": False,
                "value": event_contexts,
            },
            "LABELS": {
                "type": -1,
                "description": "",
                "is_locked": False,
                "value": event_labels,
            },
            "DESCRIPTIONS": {
                "type": -1,
                "description": "",
                "is_locked": False,
                "value": event_descriptions,
            },
            "TIMES": {
                "type": 4,
                "description": "",
                "is_locked": False,
                "value": event_times,
            },
            "ICON_IDS": {
                "type": 2,
                "description": "",
                "is_locked": False,
                "value": event_iconsid,
            },
        }
`

**Comment by ErDelhaye** [comment]
> Hi! This is how I add events from a BTS MDX file to a c3d. It's not pretty, but might be of use. Tested it with Mokka:
> 
> ```python
>    def load_events(self):
>         # Loading events from the mdx
>         events = self.mdx.trial.static.events
>         eRHS = events["eRHS"].data
>         eLHS = events["eLHS"].data
>         eRTO = events["eRTO"].data
>         eLTO = events["eLTO"].data
> 
>         event_length = len(eRHS) + len(eRTO) + len(eLHS) + len(eLTO)
>         event_contexts = (
>             ["Right"] * len(eRHS)
>             + ["Right"] * len(eRTO)
>             + ["Left"] * len(eLHS)
>             + ["Left"] * len(eLTO)
>         )
>         event_labels = (
>             ["Foot Strike"] * len(eRHS)
>             + ["Foot Off"] * len(eRTO)
>             + ["Foot Strike"] * len(eLHS)
>             + ["Foot Off"] * len(eLTO)
>         )
>         event_descriptions = [""] * event_length
>         event_iconsid = (
>             [1] * len(eRHS) + [2] * len(eRTO) + [1] * len(eLHS) + [2] * len(eLTO)
>         )
>         event_times = eRHS + eRTO + eLHS + eLTO
>         event_times = np.array(
>             [j for i in zip(list([0] * event_length), event_times) for j in i]
>         )
> 
>         self.c3d["parameters"]._storage["EVENT"] = {
>             "__METADATA__": {"DESCRIPTION": "Events", "IS_LOCKED": False},
>             "USED": {
>                 "type": 2,
>                 "description": "Total amount of events",
>                 "is_locked": False,
>                 "value": [event_length],
>             },
>             "CONTEXTS": {
>                 "type": -1,
>                 "description": "",
>                 "is_locked": False,
>                 "value": event_contexts,
>             },
>             "LABELS": {
>                 "type": -1,
>                 "description": "",
>                 "is_locked": False,
>                 "value": event_labels,
>             },
>             "DESCRIPTIONS": {
>                 "type": -1,
>                 "description": "",
>                 "is_locked": False,
>                 "value": event_descriptions,
>             },
>             "TIMES": {
>                 "type": 4,
>                 "description": "",
>                 "is_locked": False,
>                 "value": event_times,
>             },
>             "ICON_IDS": {
>                 "type": 2,
>                 "description": "",
>                 "is_locked": False,
>                 "value": event_iconsid,
>             },
>         }
> `
> ```

thank you !! :)

**Comment by marnunez** [comment]
I haven't used this code in a while, but I think it works because I write straight into `_storage`.

**Comment by marnunez** [comment]
The ICON_IDS I belive are a Mokka thing. The value determines if the triangle that marks the event goes face up or face down

**Comment by pariterre** [comment]
Hi @marnunez 
Long time no see, hope you are good! 
```
self.c3d["parameters"]._storage["EVENT"]
```
This indeed probably works, but I should provide a better way to add events, since you are directly writing to internal variables! But as you said, it probably works just fine haha

@ErDelhaye 
```
newC3D['header']["events"]["size"] = len(events_labels)
```
Adding something to the `header` won't do anything. This is completely discarded and recalculated when you write the new c3d file. That is to make sure the c3d is sane. The event must be added to the parameter EVENT. Actually @marnunez you could have used the `add_parameter` method of ezc3d.c3d to add all these parameters :P
I could add a `add_event` function that would internally call the `add_parameter` method too

**Comment by marnunez** [comment]
Hi @pariterre! I've been working in other projects, haven't been working with c3Ds in a long while. So much so that I think that hacky code I wrote is older than your rework of the python bindings. Haven't looked as to how specs treat events, might be just some special case parameters. So, like you say, maybe it would suffice with `add_parameter` and some documentation.

**Comment by ErDelhaye** [comment]
Hi Guys, thanks for your answers ! 

I had been confused by the c3d.org documentation, talking about headers ! 
If I just have to use the "addParameters" function, then I should handle it ! :) 
Thanks for your implications, I really appreciated ! 
Erwan

**Comment by pariterre** [comment]
I added an add_event method to c3d so it is easier to add in #207 !
Enjoy!
