### ISSUE TITLE
Converting to a Dataframe in Python

### ISSUE THREAD

**Issue by n2d7** [pyomeca/ezc3d#208]
Hi,
How can I convert the c3d data to a dataframe in python? 
Ideally, I want it to have this format for headers

`time, MARKER_1_X, MARKER_1_Y, MARKER_2_Z, ..., MARKER_N_Z`

after the line `c = c3d(input_file)` I'm not sure how to extract the marker names and location data from the object. Appreciate any help, thanks!

**Comment by pariterre** [comment]
Hi @n2d7 
The Pyomeca (https://github.com/pyomeca/pyomeca) toolbox uses ezc3d as c3d backend reader and stores the data into a pandas data frame (actually an xarray).
I therefore suggest the use of this library. That said, I am not familiar myself with pandas/xarray data storage.

I you just want the names of the markers and the 3d trajectories, as shown in the readme, you can do:
```
names = c['parameters']['POINT']['LABELS']['value']
points = c['data']['points']
```
Cheers

**Comment by dubergonzoni** [comment]
Hi @n2d7 

from pyomeca import Markers

Reading the data
data_path = "path_to.c3d"
markers = Markers.from_c3d(data_path, prefix_delimiter=":")

Converting to pandas DataFrame
df = markers.meca.to_wide_dataframe()
