### ISSUE TITLE
How to install using Compiling method?

### ISSUE THREAD

**Issue by miraliahmadli** [pyomeca/ezc3d#211]
I am trying to install it using compiling method, but the README file looks very ambiguous. Can you please provide tutorial on how to install it with CMAKE? 

I did not understand how to set the CMAKE variables and which commands to run in order to compile. I want to use Python3 binding.

Is it possible to provide some simple guidance on how to do it?

**Comment by pariterre** [comment]
Dear @miraliahmadli 
I already have made a video for showing how to compile here: https://www.youtube.com/watch?v=gWno_NXrITA&list=PLGv2qjI0aixmAyd2dEIyj-KAsIphi1G_S&index=1&t=75s
However, it is on Windows using the CMake-Gui, which will be drastically different for other platforms.
I cannot help you much right now as you did not provide which platform you are using.

That said, if your goal is only to use ezc3d and not modify it and that you are using the Python binder, I honestly don't see any reason to compile for yourself. I would suggest to simply download and install the precompiled binaries hosted on anaconda. You can go to anaconda.org and find them, or much more easily use a client such as `miniconda` to download and install for you, as shown in https://github.com/pyomeca/ezc3d#how-to-install

Sorry to not being able to help you more, if you need more assistance, please provide a more detailed explanation of the problems you are facing :)

**Comment by miraliahmadli** [comment]
Thanks for reply @pariterre 

I am trying to install it on macOS Big Sur. I don't want to use conda or miniconda, so I was looking for a way to install from source. Looks like pip installation is not possible, so is there any way to install on macOS without conda or miniconda?

**Comment by pariterre** [comment]
Hi @miraliahmadli 
Sorry, I haven't seen your answer..
What do you mean by installing? I you mean precompiled binaries, the only available are from conda. That said, you probably don't have to install anaconda, You can manually download them from the anaconda.org website (channel conda-forge)
