### ISSUE TITLE
Python bindings incompatibility with Opensim 4.3

### ISSUE THREAD

**Issue by marnunez** [pyomeca/ezc3d#220]
Hi @pariterre! I've a weird problem with ezc3d + opensim 4.3

In a clean conda env:

```batch
cd c:\Opensim 4.3\sdk\Python
call conda create -c conda-forge -n Opensim python=3.8 numpy -y
call conda activate Opensim
python setup.py install
python -c "import opensim"
```
works fine. Yet including ezc3d...

```batch
cd c:\Opensim 4.3\sdk\Python
call conda create -c conda-forge -n Opensim_ezc3d python=3.8 numpy ezc3d -y
call conda activate Opensim_ezc3d
python setup.py install
python -c "import opensim"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\OpenSim 4.3\sdk\Python\opensim\__init__.py", line 7, in <module>
    from .common import *
  File "c:\OpenSim 4.3\sdk\Python\opensim\common.py", line 13, in <module>
    from . import _common
ImportError: DLL load failed while importing _common: No se encontró el proceso especificado.
```

I'm using Python 3.8 (required for OpenSIM 4.3), Windows 10 x64.

Any suggestions? This might be an OpenSIM issue though

**Comment by pariterre** [comment]
@marnunez 
There is another person who experienced problem recently when having both OpenSim and ezc3d installed (@mrrezaie, issue https://github.com/pyomeca/ezc3d/issues/201 and https://github.com/opensim-org/opensim-core/issues/3066). At the time, I thought the problem came from the fact that OpenSim version is slightly, so installing ezc3d via conda would download a different .dll, but override the previous one. 

After thinking about it further, I think this was a red hearing though. Since the two versions have the same API, replacing the DLL should only upgrade (or downgrade) ezc3d's version. Unless it is compiled with -fPIC (which would produce a SegFault I think instead of a cannot find DLL), it should therefore be fine. I suspect that the actual problem is that OpenSim is compiled in 32-bits, which creates a major conflict: so either OpenSim cannot load the 64-bits dll from conda, or Python cannot load the 32-bits from OpenSim).

Could you confirm that OpenSim is in 64-bits

**Comment by marnunez** [comment]
OpenSIM GUI is x64, checked the dlls with Dependency Walker. Everything seems x64
![image](https://user-images.githubusercontent.com/1470552/131716719-3bd70857-04e1-4645-bb77-09b8e78c032e.png)

**Comment by marnunez** [comment]
In OpenSIM GUI's continuous integration (https://github.com/opensim-org/opensim-gui/actions/runs/1184472064/workflow), in all dependencies (including ezc3D, which by default is on) and opensim-core, cmake is configured with the "-A x64" flag. So yeap, x64

**Comment by marnunez** [comment]
In my case, renaming OpenSIM's ezc3d.dll doesn't seem to solve the problem.

**Comment by pariterre** [comment]
Could you try the opposite when you install? That is installing ezc3d first and then opensim (in two different lines of code)?

**Comment by marnunez** [comment]
Installing either ezc3d or OpenSIM first doesn't change anything. But I think it's a PATH thing:

If I force "C:\OpenSIM\bin" to the front of the PATH variable again, opensim works fine. However, when I try to import ezc3d:

```batch
call conda env remove -n Opensim_with_ezc3d
call conda create -c conda-forge -n Opensim_with_ezc3d python=3.8 numpy ezc3d -y
call conda activate Opensim_with_ezc3d
python setup.py install
set PATH=C:\OpenSIM 4.3\bin;%PATH%
python -c "import ezc3d"


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\envs\Opensim_with_ezc3d\lib\site-packages\ezc3d\__init__.py", line 6, in <module>
    from . import ezc3d
  File "C:\ProgramData\Miniconda3\envs\Opensim_with_ezc3d\lib\site-packages\ezc3d\ezc3d.py", line 13, in <module>
    from . import _ezc3d
ImportError: DLL load failed while importing _ezc3d: No se encontró el proceso especificado.
```

**Comment by marnunez** [comment]
> Could you try the opposite when you install? That is installing ezc3d first and then opensim (in two different lines of code)?

That batch files does that: first python + ezc3d, then OpenSIM. Tried python + OpenSIM, then ezc3D, with the same result

**Comment by marnunez** [comment]
I think that after activating the conda environment, everything within that environment loads first in the PATH. That's why ezc3d works and OpenSIM doesn't, regardless of the install order.

**Comment by pariterre** [comment]
Sorry for the late answer, I did not receive an email saying you answered back!

I see... I am not sure there is an easy way to fix that.. changing the name of ezc3d.dll will change it in OpenSim as well, leading us nowhere... The only workaround I see right now is to modify the CMakeLists file of ezc3d when OpenSim clones it to build ezc3d to change the name of the project (and therefore ezc3d.dll file, but only in opensim). This is convoluted and not maintainable.
A third option would be to change the PATH according to what needed, or to remove ezc3d folder from the path completely, but it is annoying...
A last option would be to use the exact same dll for both (meaning you are using ezc3d from the same version opensim compiled from. Everything must be the exact same though... Architecture, optimization level... OH! I think I know.. I think OpenSim is compiled with RelWithDebInfo, while I compile ezc3d using Release, making them incompatible even though they are both 64bits. I am not sure how to confirm this though...

**Comment by marnunez** [comment]
We could ask the OpenSIM devs to rename their library to something like osimEzc3d.dll, so that they can always make sure they use their own version of the library. I think they do the same with other dependencies.

As things are right now, one can't use both OpenSIM and ezc3d in the same jupyter notebook, which is a real shame

**Comment by pariterre** [comment]
I am the maintainer for ezc3d in OpenSim, I can give a try, even though I am not sure how!
I keep you posted

**Comment by pariterre** [comment]
I've had a look at the OpenSim CMakeLists.txt. There is a way to change the name of the library, but it really feels like a hack... The suggestion I have is to make sure that the library you are using is the same as the opensim one. Like this, there is no version clash anymore... 

Soory about that..

**Comment by marnunez** [comment]
Hi @pariterre! So, to be clear, we should always be matching conda's ezc3d versions with the one built in OpenSIM, right?

**Comment by marnunez** [comment]
That would mean that, as of today, we can only install OpenSIM 4.3 along ezc3d Relase 1.4.3

**Comment by pariterre** [comment]
That is correct, I am currently preparing a PR to update OpenSim to the newest version, but obviously, it won't get to OS before the next official release, unless you are building OS for yourself...
