### ISSUE TITLE
Add copy method

### ISSUE THREAD

**Issue by Kilidsch** [pyomeca/ezc3d#221]
Hello 👋 

I'd like to propose a `copy`-method, just like the one from NumPy, i.e. a method which allows making a deep copy of the data instead of a shallow one. This way we still have an efficient assignment, but a "real" copy is possible without re-reading the file (our current work-around).

Would that be possible?

**Comment by pariterre** [comment]
Hi @Kilidsch 

That's is an interesting idea! Do you mean directly in CPP code or from the Python binder? Do you have a sample code so I could more understand the use-case of a deep-copy? (For instance, is this just the arrays, or the actual swig pointer too that should be copied?)

Thanks!

**Comment by Kilidsch** [comment]
Hi @pariterre 

Our usecase was splitting one C3D file into multiple (+ a bit of processing on these files).

This is something currently done in Python, so I would appreciate if it would be accessable from there, but a copy method could probably be implemented easier in C++, wouldn't it?

So, a simple sample would be something like this (a bit simplified; hope I didn't break it):
```python
c3dList = []
print("Split and crop Xsens data.")
for i in range(Ntrj):
  c3dPart = ezc3d.c3d(args.moCapFn) # instead of deepcopy
  fr, to = getFromTo(i) # get start and end sample
  c3dPart['data']['points'] = c3dPart['data']['points'][:,:,fr:to]
  c3dPart['data']['meta_points']['residuals'] = c3dPart['data']['meta_points']['residuals'][:,:,fr:to]
  c3dPart['data']['meta_points']['camera_masks'] = c3dPart['data']['meta_points']['camera_masks'][:,:,fr:to]
  c3dPart['header']['points']["first_frame"] = fr
  c3dPart['header']['points']["last_frame"] = to-1
  c3dPart['parameters']['TRIAL']['ACTUAL_START_FIELD']['value'][0]=fr+1
  c3dPart['parameters']['TRIAL']['ACTUAL_END_FIELD']['value'][0]=to
  c3dPart['parameters']['POINT']['FRAMES']['value'][0] = to-fr
  c3dList.append(c3dPart)
```

Things like `POINT::LABELS` and so on stay the same, so a copy is really helpful. Especially since we don't know which additional parameter fields we want to add in the future.

**Comment by pariterre** [comment]
Hi @Kilidsch !

The PR #222 added the capability to deepcopy the c3d Class in Python. That should greatly simplify your code!

Thanks for the suggestion :-)

**Comment by Kilidsch** [comment]
Hi @pariterre 

Thank you very much!
I'll try it out as soon as it is released in conda-forge.

One question about the test though:  
Shouldn't these be **not** equal? Since you change the deepcopy, but not the original:
`np.testing.assert_almost_equal(c3d["data"]["points"][3, :, :], c3d_deepcopied["data"]["points"][3, :, :])`

(I have no experience with testing numpy stuff, excuse me if I just understand that code wrong)

**Comment by pariterre** [comment]
Hi again!

This 4th row is a row of 1 (to match the homogenous matrix size of 4x4. This is why they should be equal :)

**Comment by Kilidsch** [comment]
I completely missed that working on the 4th row only :sweat_smile:

**Comment by pariterre** [comment]
Once you have tested, let me know if it works, we will close the issue afterward!

**Comment by Kilidsch** [comment]
Works like a charm!

Thank you again. 😃
