### ISSUE TITLE
mamba as an alternative to conda

### ISSUE THREAD

**Issue by mrrezaie** [pyomeca/ezc3d#223]
Hi,

Recently, Anaconda has blocked the IP of my country and conda cannot download any packages from any channels. I found mambaforge as an alternative to official miniconda or anaconda:
https://github.com/conda-forge/miniforge#mambaforge

and EZC3D can be downloaded and installed by this:
`mamba install ezc3d`

Much easier and faster!!!

Regards,
Mohammadreza

**Comment by pariterre** [comment]
Dear @mrrezaie 

I am sorry for this unfair situation.. thanks for sharing this workaround. Hopefully, it can help someone else that is in a similar situation.

Kind regards
