### ISSUE TITLE
ezc3d for python can't open c3d file which is export from motion

### ISSUE THREAD

**Issue by Lance-Tin** [pyomeca/ezc3d#225]
hello,

first, thank you for your sharing of this code! I meet some mistakes when i use the API of python to read the c3d file:

code:
```python
path3 = 'D:/.../wang_dat/zhangjing_00_3.c3d'
c3ds = ezc3d.c3d(path3, extract_forceplat_data=True)
...
...
```

--------------
Error: (from jupyter notebook)
C:\...Anaconda3\lib\site-packages\ezc3d\__init__.py in __init__(self, path, extract_forceplat_data)
    126             self.c3d_swig = ezc3d.c3d()
    127         else:
--> 128             self.c3d_swig = ezc3d.c3d(path)
    129 
    130         self.extract_forceplat_data = extract_forceplat_data

C:\...\Anaconda3\lib\site-packages\ezc3d\ezc3d.py in __init__(self, *args)
   1684 
   1685     def __init__(self, *args):
-> 1686         _ezc3d.c3d_swiginit(self, _ezc3d.new_c3d(*args))
   1687 
   1688     def console_print(self):

OSError: Could not open the c3d file: iostream stream error
----------------

the c3d file can be read in "VBC3Deditor ", what'more, when i use "QUALISYS" to export the c3d file again,  it's run.

**Comment by pariterre** [comment]
Hello!

Both files you provided read well here (with and without extract_force_plate=True)

I'd suggest that the path you provided to ezc3d (`path3 = 'D:/.../wang_dat/zhangjing_00_3.c3d'`) cannot exist (D: is a root, and ... won't be able to go back)

Good luck!
