### ISSUE TITLE
Re-referencing function 

### ISSUE THREAD

**Issue by cdriehm** [pyomeca/ezc3d#230]
Hi There, i am trying to write a function to re-reference marker data to any chosen marker and am running into a strange issue where all markers before the chosen marker (earlier in the list of marker names) will be successfully re-referenced, but all after will retain their original trajectory. I must be missing something, possibly related to the way that the c3d data stucture works or how the c3d write is happening. 

Any help would be much appreciated!! 
Thanks, Chris 

`data = c = c3d(filename)
outData = data

for i in range(len(outData['parameters']['POINT']['LABELS']['value'])):
    if (data['parameters']['POINT']['LABELS']['value'][i] == refMarker):
        refx = data['data']['points'][0][i]
        refy = data['data']['points'][1][i]
        refz = data['data']['points'][2][i]
        
for k in range (len(outData['data']['points'][0])):
    for j in range (len(outData['data']['points'][0][0])):
        outData['data']['points'][0,k,j] = (data['data']['points'][0,k,j] - refx[j])
        outData['data']['points'][1,k,j] = (data['data']['points'][1,k,j] - refy[j])
        outData['data']['points'][2,k,j] = (data['data']['points'][2,k,j] - refz[j])

outData.write(outFileName)`

**Comment by cdriehm** [comment]
Figured it out! The outData = data statement doesnt create a copy, but just points to the original, which is then overwritten. Sorry to bother, thanks anyway!

**Comment by pariterre** [comment]
Good! :) 
Glad you found! Yep no copy as it would be too slow!
