### ISSUE TITLE
Unable to compile mex files using cmake

### ISSUE THREAD

**Issue by PressGO** [pyomeca/ezc3d#232]
Hi, 

Im having issues compiling the mex files. the ezc3d.dll file manage to compile but there were no mex files.
with regards to that here is the visual studio error:

Error	MSB3073	The command "setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	INSTALL	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	157	

I'm pretty sure i have admin rights but it could be something else.
Thanks!

**Comment by pariterre** [comment]
Hi there!

That definitely looks like a right level issue. What does your cmake looks like? (Can you make a print screen of the options?)

**Comment by PressGO** [comment]
Sorry for the late reply.

Another question, is it possible to get the model outputs such as joint
angles in ezc3d?

**Comment by pariterre** [comment]
Hi @PressGO 
I assume you are talking about Nexus generated models. If so, please note that there is no vanilla way to store such information. Therefore, the solution Vicon found was to store these information as points. So, you will find these data in data["points"]. You can have a look a the parameters point label to know what column correspond to what!
