### ISSUE TITLE
Ezc3d couldn't open c3d file with path syntax including ".."

### ISSUE THREAD

**Issue by AurelienRenou** [pyomeca/ezc3d#236]
Hello, 
There was a problem when we tried to open a c3d file that is in a another folder which is not in the current one.
We used /.. to go back, and chose the folder we wanted.
```python
root_path = "/".join(__file__.split("/")[:-1]) + "/.."
c3d_path = root_path + "/data/F0_boire_05.c3d"
```
Here is the error message:

`Traceback (most recent call last):
  File "C:\Users\renou\Documents\Stage_immersion\bioptim_exo\tracking\test_load_experimental_data.py", line 16, in <module>
    data = LoadData(biorbd_model, c3d_path)
  File "C:\Users\renou\Documents\Stage_immersion\bioptim_exo\tracking\load_experimental_data.py", line 75, in __init__
    self.c3d_data = C3dData(c3d_file)
  File "C:\Users\renou\Documents\Stage_immersion\bioptim_exo\tracking\load_experimental_data.py", line 9, in __init__
    self.c3d = c3d(file_path)
  File "C:\Users\renou\miniconda3\envs\env_stage\lib\site-packages\ezc3d\__init__.py", line 129, in __init__
    self.c3d_swig = ezc3d.c3d(path)
  File "C:\Users\renou\miniconda3\envs\env_stage\lib\site-packages\ezc3d\ezc3d.py", line 1686, in __init__
    _ezc3d.c3d_swiginit(self, _ezc3d.new_c3d(*args))
OSError: Could not open the c3d file: iostream stream error
Process finished with exit code 1`

We tried to debug printing the path that was actually used in ezc3d:
https://github.com/pyomeca/ezc3d/blob/0d3198586ba84d6799e11a6b12742b5596a11c90/binding/python3/__init__.py#L124-L129

If we run the script, the path used by ezc3d was 
```python
"/../data/F0_boire_05.c3d"
```
and it doesn't worked, the first "/" character seemed to cause the issue.

In debug mode, the path was
```python
"C:/Users/renou/Documents/Stage_immersion/bioptim_exo/tracking/../data/F0_boire_05.c3d"
```
And then, it was working.

We didn't find the reason, but we found a solution, if we write directly the "../" in the path string, it worked fine:
```python
c3d_path = "../data/F0_boire_05.c3d"
```

**Comment by pariterre** [comment]
Hi @AurelienRenou 
It definitely can open file with ".." as in your solution you use it! Are you sure the path was actually the right one?

**Comment by Ipuch** [comment]
I confirm the path was the right one.

**Comment by pariterre** [comment]
I confirm it is not

**Comment by pariterre** [comment]
import os
c3d_path = os.path.abspath(__file__)
print(c3d_path)
