### ISSUE TITLE
 how to modify the data of the force platform

### ISSUE THREAD

**Issue by jxm122903** [pyomeca/ezc3d#237]
Hello！
Thank you for sharing your code, I'm having some problems and looking for your help. You mentioned that EZC3D is an easy to use modifier for C3D format files. So how to modify the data of the force platform?
If I want to modify the position of the center of pressure and the magnitude of the force, how should I do it?
Thanks in advance.

**Comment by pariterre** [comment]
Hi @jxm122903 !
Force platform is really a special case in a c3d. The data of the force platforms are stored in Analog. The force plateform module analyses the stored data so any user can use them directly, but it does not go backward (for instance, changing values in a force platform structure won't affect the underlying c3d). The reason for that is technical, but in a nut shell, it would be impossible to tell what was the original way the data were stored (there are about 7 ways force platform data can be stored, and they are all incompatible with each other) and would likely result in a invalid c3d.

For a lay user to change the data of a specific force platform, one must change the values of the corresponding ANALOG in DATA. That said, it implies that you know how to interpret correctly this matrix. For that, you can refer to the C3D manual, which is available here https://www.c3d.org/docs/C3D_User_Guide.pdf
The easiest to change is the Type-2 force platform, but that entirely depends on the software you used to create the c3d in the first place

**Comment by jxm122903** [comment]
Hi @pariterre !
Thank you for your quick response！
Best Regards
