### ISSUE TITLE
Support for Rotation Data Type

### ISSUE THREAD

**Issue by teliason** [pyomeca/ezc3d#239]
I am trying to open a c3d file created by Theia and seem to be unable to access the Rotation data using ezc3d.  https://www.c-motion.com/v3dwiki/index.php?title=ROTATION_DATA_TYPE

I can see all of the rotation parameters that are stored to the file, but not the actual data itself.  Is this something that ezc3d can do or will it need to be customized to read rotation data?  

An example c3d file with rotations included can be download from the above link.

**Comment by pariterre** [comment]
Dear @teliason 
Ezc3d does not support yet ROTATION_DATA_TYPE as I was not aware yet of its existance!

This is something I can work on. I will not be able to work on this before next weekend though. Do you have any problem waiting up to that point?

**Comment by teliason** [comment]
I'm happy to wait, I really appreciate your willingness to work on adding that feature so quickly.  I've only recently found Ezc3d but has been great to work with so far, you're providing a great service for the community.  Keep up the good work!

**Comment by pariterre** [comment]
Hi @teliason 
That was much painful than expected, but the Rotation support is implemented (except for Matlab). I'll push it to conda soon :)

**Comment by teliason** [comment]
Awesome! I really appreciate you tackling that so quickly.  I'll be looking for the update to conda and will download and get testing right away.

**Comment by pariterre** [comment]
@teliason 
Just so you know, I realized I forgot to manage the "DATA_START" parameter, which is very important for writing. So I'll fix that before pushing to conda, but it should not be too long :)

**Comment by pariterre** [comment]
This is now fully merged and a release was made. Anaconda should be granted with the release 1.4.8 in a couple of hours 
Thanks for the request :)

**Comment by pariterre** [comment]
#242

**Comment by teliason** [comment]
Awesome, thank you so much.  I grabbed the updated package and did some preliminary testing and everything appears to be working as expected.  I really appreciate you adding this functionality so quickly.
