### ISSUE TITLE
Conda version and matlab

### ISSUE THREAD

**Issue by mickaelbegon** [pyomeca/ezc3d#24]
Hi Benjamin, 
When ezc3d is installed from conda, does the matlab binding is also installed?

**Comment by romainmartinez** [comment]
Since version 0.3.0, Matlab binding is no longer included in the binaries hosted on conda. 

You must build ezc3d yourself with CMake and Matlab binding enabled.

**Comment by pariterre** [comment]
That is exact. Conda is more designed to work with python, this is why that decision was made. However, I could upload the binaries to mathworks if you think that make sense :)

**Comment by jimmyDunne** [comment]
My two cents— I would recommend not uploading binaries and rather having a robust local build system for the bindings. Uploads get out of date very quickly and you will be expected to maintain the uploads for every system (Operating system and version of Matlab) imaginable.

**Comment by pariterre** [comment]
I've had a quick look with octave, but conda-forge doesn't even provide windows binaries...
