### ISSUE TITLE
Error Writing Rotation Data

### ISSUE THREAD

**Issue by teliason** [pyomeca/ezc3d#244]
Thanks again for adding in support for rotation data so quickly.  

I've been testing the latest release you pushed to conda and on the reading side everything seems to be working great.  However, I'm running into an issue when trying to write a new c3d file with rotation data included.  When I add any parameters to the 'ROTATION' group or if I add any data to 'rotations' I get the same issue.  It will save out the c3d file without giving any errors, but I cannot read that c3d file back in.  

When reading the produced c3d I get the following error  "RuntimeError: Could not read the processor type."  Also I've tried loading it into MlsViewer and similarly it appears to be corrupted and cannot view the different parameter groups.  

I'll generate some sample code to reproduce the error and post here later today.

**Comment by teliason** [comment]
Here is some sample code that reproduces the error.

```
import numpy as np
import ezc3d

c3d = ezc3d.c3d()

c3d['parameters']['POINT']['RATE']['value'] = [100]
c3d['parameters']['POINT']['LABELS']['value'] = ('point1', 'point2', 'point3', 'point4', 'point5')
c3d['data']['points'] = np.random.rand(4, 5, 100)
c3d['data']['points'][1, :, :] = 2
c3d['data']['points'][2, :, :] = 3

c3d.add_parameter('ROTATION','RATE', [100])
c3d.add_parameter('ROTATION', 'LABELS', ["Rot1", "Rot2"])
c3d['data']['rotations'] = np.random.rand(4,4,2,100)

c3d.write("reproduce_error.c3d")
read_c3d = ezc3d.c3d('reproduce_error.c3d')
```

**Comment by pariterre** [comment]
I'll have a look :)

**Comment by pariterre** [comment]
The issue was that the mandatory USED parameter for the ROTATION group was not set automatically. Adding 
`c3d.add_parameter('ROTATION','USED', [2])` in your code solved the problem. But this is not convenient! 
So the PR #246 Fixed this, and also automatically sets the RATE to be equal to the one from the POINT.
Hopefully this is all good now!

**Comment by teliason** [comment]
Awesome, thank you so much for fixing that.  I was hoping it was going to be something simple.
