### ISSUE TITLE
Regarding ezC3D installing in matlab 

### ISSUE THREAD

**Issue by jobingthampi** [pyomeca/ezc3d#245]
Hi i recently download OpenSim version 4.3. So, I need to process C3D data in OpenSim and i was trying to install the binaries and this was the error message I got 'failed with initial frozen solve. Retrying with flexible solve' when I executed in miniconda. Since I am not able to install this, Iam not able to move forward. Please help me as early as possible.

**Comment by pariterre** [comment]
Hi there!
For OpenSim (I am assuming you are building OpenSim for yourself, meaning that you don't use the prebuild OpenSim), you should not install ezc3d yourself, but you should use the superbuild and turn c3d file to ON. It will automatically download, compile and install ezc3d for you. 
Please note, that building for yourself is very likely to result in incompatibilities with OpenSim as it runs (and expect) an older version of ezc3d

**Comment by jobingthampi** [comment]
How can I turn that on?

**Comment by pariterre** [comment]
It is when you build the `dependency` folder

**Comment by jobingthampi** [comment]
Sir, I just started Opensim. So the professor gave me some C3D files and asked me to read/process in opensim. So when I went through opensim website they told it is easy to use EZC3D to read c3d files. So can you explain bit clearly how to proceed.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pariterre** [comment]
Hi again, 
As I suggested, you are not supposed to do anything specifically related to ezc3d directly. Ezc3d is just the backend used by OpenSim to load c3d data. As a lay user, you don't even have to know that ezc3d is used at all (for instance BTK is another library that can be used, but the user cannot know which one is used by OpenSim). This is an information important for programmers of the core of OpenSim, but not at all for an user like yourself. 

I think your question should be asked to an OpenSim forum directly as sou seem to be struggling with usage of the OpenSim software (see: https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB). Also, I cannot be of much help as I don't use OpenSim myself and that I am not part of the OpenSim development team. My sole role in OpenSim regarding ezc3d was to implement it in the backend few years ago.
