### ISSUE TITLE
Data_Start Size wrong data type

### ISSUE THREAD

**Issue by teliason** [pyomeca/ezc3d#249]
We found a small bug where the data_start parameter was being saved as 8 bit instead of 16 which was causing an issue when the data_start parameter needed to be more than 255 for the rotations.  

Changing the RotationsDataStartSize datatype from BYTE to WORD in DataStartInfo.h fixed this issue for us but wanted to let you know so you can make the update on the repository.  

Also small issue with the updated setup.py when building on our end.  We had to take out the quotes on the following lines 
        '-DCMAKE_INSTALL_BINDIR="ezc3d"',
        '-DCMAKE_INSTALL_LIBDIR="ezc3d"'
and change it to 
        '-DCMAKE_INSTALL_BINDIR=ezc3d',
        '-DCMAKE_INSTALL_LIBDIR=ezc3d'

Otherwise we would get a error as it would insert the quotes into the path resulting in an Invalid argument error.
.../ezc3d/_skbuild/win-amd64-3.7/cmake-build/CMakeFiles/Export/**"ezc3d"**/cmake/ezc3d/ezc3dTargets.cmake": Invalid argument

**Comment by pariterre** [comment]
Hi @teliason !
Thanks for these :) Do not hesitate to actually pull request your changes, so like that you are credited for the bug fix in the code
