### ISSUE TITLE
Apple M1 packages not found in conda

### ISSUE THREAD

**Issue by xubuild** [pyomeca/ezc3d#251]
Hi,
It failed when trying ``` conda install -c conda-forge ezc3d``` in Apple M1 platform.
There is no arm64 package in https://anaconda.org/conda-forge/ezc3d. 
Could you please add support for it? Thanks!

**Comment by pariterre** [comment]
Hi @xubuild 
I would very much like, but I must admit I have no clue what I am supposed to do for that... I already added the binaries for osx, I genuinely thought it was the only required format for mac... Can you point me out one package that provides Apple M1? I could try to copy what they are doing..

**Comment by xubuild** [comment]
Hi,
Thanks for ther repaly! I can see numpy has the "osx-arm64" build:
https://anaconda.org/conda-forge/numpy

**Comment by pariterre** [comment]
I pushed everything on anaconda, could you have a try if it works?

**Comment by xubuild** [comment]
Hi,
I still got the not found error:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - ezc3d

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
  
```
I also checked https://anaconda.org/conda-forge/ezc3d, there is no "osx-arm64" package.

Note: it's searching in "osx-arm64" rather than "osx-64"

Thanks!

**Comment by pariterre** [comment]
Hello @xubuild 
I am pleased to annonced that ezc3d is (at last) available on conda-forge for osx_arm64 :)
`conda install -c conda-forge ezc3d` command should therefore work now!
