### ISSUE TITLE
Can't open file with accented letters in path on Windows

### ISSUE THREAD

**Issue by felixchenier** [pyomeca/ezc3d#252]
Salut Benjamin

On Windows 11, I systematically get an OSError if there's an accented letter in the filename or path. This error doesn't happen on macOS.

```
>>> import ezc3d
>>> a = ezc3d.c3d('tést/WALK05.c3d')

Traceback (most recent call last):

  File "C:\Users\felix\AppData\Local\Temp\ipykernel_2928\3918078179.py", line 1, in <cell line: 1>
    a = ezc3d.c3d('tést/WALK05.c3d')

  File "C:\Users\felix\miniconda3\envs\mosa\lib\site-packages\ezc3d\__init__.py", line 128, in __init__
    self.c3d_swig = ezc3d.c3d(path, ignore_bad_formatting)

  File "C:\Users\felix\miniconda3\envs\mosa\lib\site-packages\ezc3d\ezc3d.py", line 1901, in __init__
    _ezc3d.c3d_swiginit(self, _ezc3d.new_c3d(*args))

OSError: Could not open the c3d file: iostream stream error
```

ezc3d version:
```
C:\Users\felix>conda list ezc3d
# packages in environment at C:\Users\felix\miniconda3\envs\mosa:
#
# Name                    Version                   Build  Channel
ezc3d                     1.4.10           py38h9e3ed74_0    conda-forge
```

**Comment by felixchenier** [comment]
It also happens with spaces in path. For example, if the file in in the "test 1" folder, either of these forms (backslashed or not) generates the error:

    a = ezc3d.c3d('test 1/WALK05.c3d')
    a = ezc3d.c3d('test\ 1/WALK05.c3d')

Same output.

Again, it only happens on windows, not on macOS.

**Comment by pariterre** [comment]
Hi @felixchenier !
I suspect that on Windows, one must specify the path with double blackslashes (\\) instead of a single forward slash (/). Can you confirm that `a = ezc3d.c3d('tést\\WALK05.c3d')` does not work either?

**Comment by felixchenier** [comment]
Hi @pariterre 

No, it's not that, normally slashes and double-backslashes work equally in Python, at least on pure-python functions. However I don't know why, I tried again and names with spaces worked this time. But not names with accented letters.

To test it as deep as I can, I copied a test file in several subfolders and with several names to see what works and what doesn't work:

    test.c3d
    testé.c3d
    test test.c3d
    folder\test.c3d
    folder\testé.c3d
    folder\test test.c3d
    folder 1\test.c3d
    folder 1\testé.c3d
    folder 1\test test.c3d

    from ezc3d import c3d
    c3d('test.c3d')  # works
    c3d('testé.c3d')  # doesn't work
    c3d('test test.c3d')  # works
    c3d('folder/test.c3d')  # works
    c3d('folder/testé.c3d')  # doesn't work
    c3d('folder\\testé.c3d')  # doesn't work
    c3d('folder/test test.c3d')  # works
    c3d('folder 1/test.c3d')  # works
    c3d('folder 1/testé.c3d')  # doesn't work
    c3d('folder 1\\testé.c3d')  # doesn't work
    c3d('folder 1/test test.c3d')  # works

As you can see it seems that as soon as there is an accented letter in the file name, it doesn't work. Probably one of those latin vs utf-8 encoding stuff.

**Comment by pariterre** [comment]
I confirm, ezc3d does not support latin (nor any of the hundreds different ASCII tables windows decided to use to (unexplicably) avoid UTF-8), but UTF-8 only. I tried it in the past, it is a nightmare to implement because it is impossible to know from a path name what convention it uses (unlike files for instance where it can be specified in the actual file). As a rule of thumb, never use special characters nor spaces in a path or file name :P

**Comment by felixchenier** [comment]
@pariterre Yes, this is what I avoid myself, but not everybody does. That's fair, I already had an idea for a workaround (try if reading the file works; if it doesn't, copy the c3d in a temp directory without special characters and read this copy).

Merci pour ton aide !

**Comment by pariterre** [comment]
Bienvenue :)
