### ISSUE TITLE
Please consider using pre-installed googletest when available

### ISSUE THREAD

**Issue by yurivict** [pyomeca/ezc3d#256]
googletest-1.11.0 is installed from a package, yet you still look for a bundled googletest.

Please consider using external googletest when available.

**Comment by pariterre** [comment]
Dear @yurivict 

Is there an issue installing a standardised version of the test suite? In my opinion, using an uncontrolled version of the test suite may result in tests failing if the API is not the same between the version used to create the tests and a local one, one may have. I feel that out of simplicity, it is actually better to stick to a uniform version of the google test suite.
