### ISSUE TITLE
Python bindings install C++ headers in include/ezc3d

### ISSUE THREAD

**Issue by yurivict** [pyomeca/ezc3d#258]
These headers aren't necessary and would conflict with the ezc3d package.

FreeBSD 13.1

**Comment by pariterre** [comment]
Hi @yurivict 
I am not sure what you mean. Do you mean that "include/ezc3d" should not be installed? How one would compile against ezc3d then?

**Comment by yurivict** [comment]
> I am not sure what you mean. Do you mean that "include/ezc3d" should not be installed? How one would compile against ezc3d then?

ezc3d itself installs C++ heraders to compile with. The Python binding shouldn't install C++ headers again,

**Comment by pariterre** [comment]
Indeed, where do you see that the Python binding install headers?

**Comment by yurivict** [comment]
```python setup.py install``` installs C++ headers.

**Comment by pariterre** [comment]
I see what you mean. I honestly don't remember who introduce setup.py... The intended way to install python binder is to use make install from cmake. That said, I try to remove the headers from the setup.py file but I could not find the proper command. 

Closing this issue as it is a year long, but if you ever come back to this and have a solution, please feel free to open a pull request that solves this issue!
