### ISSUE TITLE
Could not open the c3d file: iostream error

### ISSUE THREAD

**Issue by romainmartinez** [pyomeca/ezc3d#26]
I get an error `Could not open the c3d file: iostream error` on about 80% of my c3ds.

Here is an example:

```Python
import ezc3d
c = ezc3d.c3d('my_c3d.c3d')
```

Do you have any idea where this might come from?

**Comment by pariterre** [comment]
Hi romainmartinez,

I uploaded a patch when a file is filled with zeros at the beginning of the file as the one that causes problem to you. Please tell me if it solves the problem

**Comment by romainmartinez** [comment]
Everything is working fine with the new patch :+1:
