### ISSUE TITLE
Mex files are not created

### ISSUE THREAD

**Issue by monsitacatalina** [pyomeca/ezc3d#260]
I'm traying to use the commands of the ezc3d library but I can't install it, I'm doing with cmake and visual studio but when I start to compiller the "install" file it doesn't complete the process

**Comment by monsitacatalina** [comment]
![2022-06-21 (1)](https://user-images.githubusercontent.com/107505999/174861772-5e14921b-d1a2-4971-b34b-ba0d335f4342.png)

**Comment by pariterre** [comment]
I suspect that your problem is related to the admin rights and/or the place it tries to install. 
Could you show me the values of the CMake?

**Comment by monsitacatalina** [comment]
> @pariterre 
![2022-06-22 (1)](https://user-images.githubusercontent.com/107505999/175092494-fc4196bf-81a4-42d2-946c-c5b382b1159d.png)
![2022-06-22 (2)](https://user-images.githubusercontent.com/107505999/175092507-d75c602d-d517-4316-a39d-f2fb1bc8d286.png)
![2022-06-22](https://user-images.githubusercontent.com/107505999/175092513-4e54463c-a3e0-4344-8761-81dfe3821a9e.png)

**Comment by pariterre** [comment]
Yep, your problem is the `CMAKE_INSTALL_PREFIX` and `Matlab_ezc3d_INSTALL_DIR` which points to folder you need admin rights. Either you change these folder to something without this level of rights or you launch Visual Studio with admin rights

**Comment by monsitacatalina** [comment]
@pariterre I change the folder and its ok!!! thanks
