### ISSUE TITLE
How to append a new marker with ezc3d?

### ISSUE THREAD

**Issue by doba-95** [pyomeca/ezc3d#266]
Hey all!
First of all thank you for working on this project, really appreciate it! 
I started today working with ezc3d in Python 3.9.13 and tried to append the calculated HJC location to the markers in the c3d file. However, while being able to extract the marker data and calculate the HJC location, I fail to add these as a new marker to the c3d file. Help would be much appreciated. 

Cheers 
Dominic

Here is my code (unfortunately i cannot attach the c3d). 

`from cmath import sqrt
from ezc3d import c3d 
import numpy as np
import math

def main():
    c = c3d(r'C:\Users\dominicbachmann\Documents\MAPClient\FAIWorkshop\mapclient-fai-workshop-master\wfdata\FAS-906\mocap\FAI_001_BAS_REF_001.c3d')
    #print(c['parameters']['POINT']['USED']['value'][0]); 

    point_data = c['data']['points'] #contain 4xNxT struct N = number of points , T= number of frames
    #returns all labels in c3d 
    used_labels = c['parameters']['POINT']['LABELS']['value']
    #returns number of frames in c3d
    num_frames = c['parameters']['POINT']['FRAMES']['value'][0]

    # here data names can be inputed to extract 
    RHJCm = np.zeros((num_frames, 4))
    LHJCm = np.zeros((num_frames, 4))
    list_names = ['LASI','RASI','LPSI','RPSI']
    points_HJC = dict()
    #loop extracts landmarks for calculation of HJC and adds them to list
    for i in range(num_frames):
        for n in range(len(list_names)):
            index = used_labels.index(list_names[n])
            points_HJC.update({list_names[n]: point_data[0:3, index, i]})
        RHJC, LHJC = HJC_calc(points_HJC)
        
        RHJCm[i][0:3] = RHJC
        RHJCm[i][3] = 1
        LHJCm[i][0:3] = LHJC
        LHJCm[i][3] = 1

    #here i tried (without any success to add the markers)
    c.add_parameter("POINT", "RHJC", RHJCm)
    c.add_parameter("POINT", "LHJC", LHJCm)
    print(c["parameters"]["POINT"]["LABELS"]["value"])
    # try alternative approach
    c.add_parameter('LABELS', "RHJC", RHJCm)
    print(c["parameters"]["POINT"]["LABELS"]["value"])
    used_labels = c['parameters']['POINT']['LABELS']['value']
    
    c.add_parameter("POINT","Test", [1,2,3])
    print(used_labels)
    c.write('C:/Users/dominicbachmann/Documents/MAPClient/FAIWorkshop/mapclient-fai-workshop-master/wfdata/FAS-906/mocap/FAI_001_BAS_REF_001_new.c3d')

    print("This is RHJC", RHJCm)
    print("This is LHJC",LHJCm)

#print(used_labels)

def HJC_calc(points_HJC):
    MID_ASIS = (points_HJC['RASI'] - points_HJC['LASI']) / 2 + points_HJC['LASI']
    MID_PSIS = (points_HJC['RPSI'] - points_HJC['LPSI']) / 2 + points_HJC['LPSI']

    # calc mit Pelvis Marker 
    MID_PELVIS = (MID_ASIS - MID_PSIS) / 2 + MID_PSIS

    #HJC (Harrington)
    PD = np.sum((MID_ASIS - MID_PSIS)**2, axis=0)
    PD =  np.sqrt(PD)
    
    #PD_2 = math.dist(MID_ASIS, MID_PSIS)
    #PW_2 = math.dist(points_HJC['RASI'], points_HJC['LASI'])

    PW = np.sum((points_HJC['RASI'] - points_HJC['LASI'])**2, axis=0)
    PW = np.sqrt(PW)
    
    #Create pelvic coordinate system
   
    ez_pelvis = (points_HJC['RASI'] - points_HJC['LASI']) / np.sqrt(np.sum((points_HJC['RASI'] - points_HJC['LASI'])**2, axis=0)) # z-axis of coord sys
    line_mid2mid = MID_PSIS - MID_ASIS
    dummy = np.cross(line_mid2mid, ez_pelvis)
    
    ex_pelvis = np.cross(dummy, ez_pelvis) / np.sqrt(np.sum(np.cross(dummy, ez_pelvis)**2, axis= 0))

    #y-axis
    ey_pelvis = np.cross(ez_pelvis, ex_pelvis)

    #Right Hip Joint Center
    crhip_x = (-0.24*PD-9.9) * ex_pelvis
    crhip_y=(-0.30*PW-10.9) *ey_pelvis
    crhip_z=(0.33*PW+7.3) *ez_pelvis
    RHJC=MID_ASIS+crhip_x+crhip_z+crhip_y

    #Left Hip Joint Center
    clhip_x=(-0.24*PD-9.9) *ex_pelvis
    clhip_y=(-0.30*PW-10.9) *ey_pelvis
    clhip_z=(0.33*PW+7.3) *-ez_pelvis
    LHJC=MID_ASIS+clhip_x+clhip_z+clhip_y

    return RHJC, LHJC

if __name__== "__main__":
    main()
`

**Comment by pariterre** [comment]
Hi @doba-95 
I see where the confusion comes from. Since the label is already in the POINT group, you don't have to `add_parameter` LABELS again, you just have to change the values

This snippet is a copy-paste of the doc that should help you :) 
```python
c3d['parameters']['POINT']['RATE']['value'] = [100]
c3d['parameters']['POINT']['LABELS']['value'] = ('point1', 'point2', 'point3', 'point4', 'point5')
c3d['data']['points'] = np.random.rand(4, 5, 100)
c3d['data']['points'][1, :, :] = 2
c3d['data']['points'][2, :, :] = 3
``` 
The `len` of LABELS tuple should match the number of column of `data.points`. To be sure, you can also update by hand the `USED` parameter of the `POINT` group, though it should update itself when writting 

Please note that the changes for consistency won't be reflected in the `c3d` structure, but only in the resulting c3d when written on the disk, as it resolves everything at that moment only!

**Comment by doba-95** [comment]
Hey @pariterre,
thank you for your fast response! 
I am still struggling with the appending of the new virtual markers. 
I was able to create a new lable list which includes the RHJC and LHJC marker (see code below) 
`list_of_labels = c["parameters"]["POINT"]["LABELS"]["value"]
    # append the new markers two labels list
    list_of_labels.append('RHJC')
    list_of_labels.append('LHJC')
    # assign new label list to c3d
    c['parameters']['POINT']['LABELS']['value']= list_of_labels`

I was also able to ndarray which includes the marker location
`#alternative to approach above
    RHJCm = np.zeros((4,1,num_frames))
    LHJCm = np.zeros((4,1,num_frames))

    list_names = ['LASI','RASI','LPSI','RPSI']
    points_HJC = dict()
    #loop extracts landmarks for calculation of HJC and adds them to list
    for i in range(num_frames):
        for n in range(len(list_names)):
            index = used_labels.index(list_names[n])
            points_HJC.update({list_names[n]: point_data[0:3, index, i]})
        RHJC, LHJC = HJC_calc(points_HJC)
        RHJC = np.append(RHJC, 1)
        LHJC = np.append(LHJC, 1) 
        RHJCm[:,0,i] = RHJC
        RHJCm[:,0,i] = LHJC
    final_data_points = np.zeros((4,num_points+2, num_frames))
    final_data_points[:,0:num_points,:] = point_data

    final_data_points[:,num_points:num_points+1,:] = RHJCm
    final_data_points[:,num_points:num_points+2,:] = LHJCm

    c['data']['points'] = final_data_points
`
But when I try to write the c3d I receive following error message: 
`Exception has occurred: ValueError
'c3d['data']['meta_points']['residuals']' must have its second dimension's shape equals to the number of points.
If you are modifying a pre-existing c3d, it is probably easier to delete 'c3d['data']['meta_points']' and let ezc3d create a new one by itself.`
How do i delete the meta_points?

**Comment by doba-95** [comment]
I found the command in a different issue. Sorry for not researching it before. 
I feel like my way is quite complicated. Is there an easier approach to this problem? similar to the btkappendmarker command from the btk toolkit?

**Comment by pariterre** [comment]
The main problem is that Python is an interface to the actual C++ code behind. This is why there is no vanilla ways to do that. 
The easiest way is to use `delete c3d['data']['meta_points']` (or something like that, I cannot test right now.. sorry)
