### ISSUE TITLE
Get labels for each frame from c3d file

### ISSUE THREAD

**Issue by mfalv** [pyomeca/ezc3d#272]
Hi,

How would I be able to extract the labels assigned across all frames from a c3d file using ezc3d?

Thanks.

**Comment by pariterre** [comment]
Dear @mfalv 
What do you mean by "across all frames"? Are you referring to names of the markers? If so, they do not change across frames... If so, you can get them in the parameters POINT:LABELS

Cheers

**Comment by mfalv** [comment]
Thanks @pariterre. I am looking to extract the predicted labels for the markers at each data frame - is this something feasible?

**Comment by pariterre** [comment]
@mfalv 
Just to be clear, "labels" are the actual "name" of the markers, for instance "PSIS". I do not understand what it means to have predicted names at each data frame
