### ISSUE TITLE
Error in compiling MATLAB binder

### ISSUE THREAD

**Issue by scp010** [pyomeca/ezc3d#280]
Have followed the Youtube video for compiling on Windows using CMake, and have gotten the error MSB3073 in the INSTALL project when trying to compile in Visual Studio 2019. Description is given "The command 'setlocal'", line 155, file is MIcrosoft.CppCommon.targets. I am able to build the ezc3d.dll file, but no mexw64 files are built. Similar to this issue in the comments of the video, I have tried changing to add_library instead of add_executable with no results. 

I am currently using Windows 8.1 OS, is Windows 10 required for compilation?

**Comment by pariterre** [comment]
Dear @scp010 

Usually when you see "setlocal" error, it indicates you are trying to install in a folder you don't have right access (such as Program Files). If you kept CMAKE_INSTALL_PREFIX and Matlab_ezc3d_INSTALL_FOLDER to default, they require admin access. If you change them, that should help. That said, you did not provide the full error message, which makes it a bit difficult to diagnose

Hope this helps!
