### ISSUE TITLE
Rotations are not available in MATLAB, but works in Python

### ISSUE THREAD

**Issue by mathiasbankay** [pyomeca/ezc3d#286]
Hi

I have compiled ezc3d for MATLAB with cmake following your video on youtube. Worked well.
 When I read a c3d-file generated from Theia, which includes rotations, ROTATION is available in c3d.parameters, but no rotations are available in c3d.data

Reading the same c3d in Python, [data][rotations] are availabe.

Is there anythink I did wrong?

Thank you very much for this great tool!

Best,

Mathias

**Comment by pariterre** [comment]
Hi @mathiasbankay !
There is nothing you did wrong, I simply did not implemented the Rotation yet in Matlab (assuming no one was actually interested by that!). I can look for a fix in the upcoming days!

**Comment by mathiasbankay** [comment]
Hi @pariterre!
Thank you so much, this would be very kind if you can look for a fix.

**Comment by pariterre** [comment]
PR merged! (there was a small issue on UNIX that I had to fix) 
Thanks for using ezc3d :)
