### ISSUE TITLE
Events >60s not populating correctly

### ISSUE THREAD

**Issue by KA-McDonald** [pyomeca/ezc3d#295]
Hello,

The footstrike events in my c3d are located at the following times:
57.1, 58.25, 59.51, 60.63, 61.78, 62.89, 64.02 

But when exporting the time data via event_data = c['parameters']['EVENT']['TIMES']['value'], events t>60 s have errors (t - 60):
0.63, 1.78, 2.89, 4.02, 57.1, 58.25, 59.51

I'm unsure what happens when t>120 s (I do not have a file long enough to test this).

I can make amendments within my code to accommodate the issue, but any support fixing this would be appreciated for future processing of longer trials.
Thanks!

**Comment by pariterre** [comment]
Hello there! 

That is a surprising bug! I wonder if it is not simply due to the fact that time is stored in a 8-bits fashion... That would be surprising that it is exactly 60 seconds off though.

If you happen to have a c3d that I can play with, I could have a look!

**Comment by pariterre** [comment]
Closed as stalled
