### ISSUE TITLE
Bug: Reading analogs from .c3d using Kineticstoolkit via ezc3d

### ISSUE THREAD

**Issue by zybermonk** [pyomeca/ezc3d#307]
I have some .c3d files recorded from a Mocap system. I use kineticstoolkit library (which in-turn uses **ezc3d** to read files), but it does not read the analogs from these c3d files by default. However, When I open the files in a biomechanics viewer (mokka) analogs are present. And when I export the exact file from mokka, now ktk (kineticstoolkit) reads the analogs.

Please refer to this issue on kineticstoolkit for more information: https://github.com/kineticstoolkit/kineticstoolkit/issues/219 

Talking to KTK, the issue seems to be on the ezc3d. Any assistance would be appreciated. Additionally, if you need the files before and after exporting from mokka, I can share them with you via email.

Thanks in advance.
Regards.

**Comment by pariterre** [comment]
Hi @zybermonk 

Thanks for reporting the issue, could you provide me with a faulting C3D so I can have a look a the issue

Regards :)

**Comment by zybermonk** [comment]
Hi @pariterre,
Thank you for your quick response. I have sent them to your mail that I got from your GitHub.

Looking forward to your response.
Best,
Mohan

**Comment by pariterre** [comment]
Hi @zybermonk still waiting for the c3d file!

**Comment by zybermonk** [comment]
Hi @pariterre,
I sent it to `pariterre@hotmail.com`, right after your request.
Please check your spam just in case it ended up there.

Alternatively, if you want it to an other address, I shall share them again. Let me know.
Thanks

**Comment by pariterre** [comment]
It does not seem to be in the spam... could you try same address but gmail.com?

**Comment by zybermonk** [comment]
Done.
Let me know if you received them in your gmail.

**Comment by pariterre** [comment]
Yep, got it :)

**Comment by pariterre** [comment]
Dear @zybermonk 
Sorry for the late answer, I could have a look at the data. It seems Shadow was quite loose in their implementation of the C3D format... I made a fix that overcome this. If you are able to compile ezc3d by yourself, could you have a try? If not, I can make a release which will allow you to download the latest version, but I am not 100% sure of the fix, that's why I'd like you input on: does this fix gives expected results!

**Comment by pariterre** [comment]
See #309

**Comment by zybermonk** [comment]
> Dear @zybermonk 
> Sorry for the late answer, I could have a look at the data. It seems Shadow was quite loose in their implementation of the C3D format... I made a fix that overcome this. If you are able to compile ezc3d by yourself, could you have a try? If not, I can make a release which will allow you to download the latest version, but I am not 100% sure of the fix, that's why I'd like you input on: does this fix gives expected results!


Thank you, @pariterre,
The fix seems to work and is getting us the required analogs. Really appreciate the workaround to overcome this.

Closing the issue as done.
