### ISSUE TITLE
Accessing Pose node from Theia c3d file

### ISSUE THREAD

**Issue by DocVi** [pyomeca/ezc3d#318]
Hi,

I would like to know if you store the "Pose" node (it is exists) in your ezc3d object and if we can access it through the keys.
I tried to find it but could not...
[pose_filt_0.zip](https://github.com/pyomeca/ezc3d/files/15043749/pose_filt_0.zip)

Thanks

Vincent

**Comment by pariterre** [comment]
Dear @DocVi 

I am not sure what you are calling pose. From what I see in your C3D, there is rotation data. Is that what you mean? If so, it is stored in `c3d.data.rotations`.

If it is not, I would suggest to investigate the "parameters" section (`c.parameters`)

Hope this helps!

**Comment by DocVi** [comment]
Hi,

Pose is a node that should store the tranformation matrices in a static pose.
Rotation is there of course but it corresponds to the transformation matrices of each frame.

I guess you do not see it because they might not have exported it or make it available in the c3d.

Thanks

**Comment by pariterre** [comment]
I've had another look for what would look like static pose, and it does not seem there is. If it is there, it would definitely be in the parameters.

Good luck!
