### ISSUE TITLE
ModuleNotFoundError with numpy 2.0

### ISSUE THREAD

**Issue by felixchenier** [pyomeca/ezc3d#332]
ezc3d doesn't import when NumPy 2 is installed.

# NumPy 1

```
conda create -n test1 python=3.12 numpy=1 ezc3d
```

In this case, this is the version of ezc3d that gets installed:

`ezc3d-1.5.10               |py312_python3_h265b4a9_2`

```python
>>> import ezc3d
```
works

# NumPy 2

```
conda create -n test1 python=3.12 numpy=2 ezc3d
```

In this case, this is the version of ezc3d that gets installed:

`ezc3d-1.5.10               |py312_octave_hcae72de_2`

(Note "octave" instead of "python")

```python
>>> import ezc3d
```

```
ModuleNotFoundError: No module named 'ezc3d'
```

**Comment by pariterre** [comment]
Hi @felixchenier 

Trying to force the installation of python based ezc3d when forcing numpy=2 returns an error reporting fatal incompatibility (`conda install ezc3d=*=*python* numpy=2 -cconda-forge`) 

Looking at the corresponding file in anaconda (https://anaconda.org/conda-forge/ezc3d/files) we can see that `ezc3d` is properly installed. That basically means that conda is not ready yet to install all dependencies of ezc3d if numpy 2 is required. This is not on my side I think, but only on conda-forge side which has not yet ported all their libraries to numpy 2

**Comment by pariterre** [comment]
Hi @felixchenier 

Quick update on this. I am pretty sure it all work fine now :) Moreover, as of today, ezc3d can be installed using pip (`pip install ezc3d`) which is much simpler that using conda!

Enjoy!

**Comment by felixchenier** [comment]
Yes it works!
