### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by mrrezaie** [pyomeca/ezc3d#343]
Hi @pariterre, I understand that publishing ezc3d to PyPI might be challenging and not have been a priority for you. However, it would be incredibly beneficial for many users, including myself. 
Some are only permitted to work with official Python.

I believe the GitHub Actions could build and publish it on PyPI with minimal effort. Here is a tutorial: https://medium.com/@blackary/publishing-a-python-package-from-github-to-pypi-in-2024-a6fb8635d45d

Or, even a workflow to upload the Python binaries in Releases or Artifacts would be great as well.

Thank you in advance for your time and effort.

**Comment by mrrezaie** [comment]
Hi, I found the solution; I could build ezc3d using GitHub Actions. The workflow clones ezc3d, builds it for Windows and Python 3.12, creates wheel file, and uploads it in artifacts: https://github.com/mrrezaie/testBuildEZC3D/blob/main/.github/workflows/build_ezc3d.yml

Then, the pip could install the ezc3d through the wheel file. The wheel file can also be published on PyPI for any Python user (please check the link in the previous comment).

Hope this helps.

**Comment by pariterre** [comment]
Sweet! I won't have time to implement this before the week after the next, but I come back to this beginning of November!
Thanks for searching this :)

**Comment by pariterre** [comment]
Dear @mrrezaie 

That was quite a journey... but as of today, ezc3d can be installed using pip :)


So either : 
```bash
pip install .
```

from the root folder or
```bash
pip install ezc3d
```

Enjoy!

**Comment by mrrezaie** [comment]
🙏🙏🙏
