### ISSUE TITLE
Error while re-writing a c3d Vicon file 

### ISSUE THREAD

**Issue by Fiverdug** [pyomeca/ezc3d#38]
When I try to re-write a c3d Vicon file after modifying it, I get the an error message. Here is an example:
c = ezc3dRead('ViconFile.c3d');
% [...] some modifications
ezc3dWrite('NewViconFile.c3d', c);

Error using ezc3dWrite
'parameters.ANALOG.LABELS' parameters is not accessible in the structure.

**Comment by pariterre** [comment]
Dear Fiverdug, 

Vicon omit a required parameter when they create a C3D file without analogs. When it doesn't prevent the reading of it, writting it back would generate a corrupted C3D. Thus, what ezc3d tells you are the instructions to modify the read file. 

In this case, a quick fix would be something like that: 
```Matlab
c = ezc3dRead('ViconFile.c3d');
% [...] some modifications
if ~isfield(c.parameters.ANALOG, 'LABELS')
    c.parameters.ANALOG.LABELS = {};
end
ezc3dWrite('NewViconFile.c3d', c);
```
Tell me if that does the trick!

**Comment by Fiverdug** [comment]
Yes, that solved the problem! Thanks!
