### ISSUE TITLE
Add forceplates in global reference frame

### ISSUE THREAD

**Issue by pariterre** [pyomeca/ezc3d#40]
The forceplates are given in the local reference frame instead of global reference frame...
See if something can be done

**Comment by marnunez** [comment]
Hi @pariterre! I'm trying to use ezc3d to export to c3d from tdf files, and programatically add some markers/analogs of my own in there.
BTS's TDF Inspector allows exporting of tdf files to c3d.

[BTS_C3Ds.zip](https://github.com/pyomeca/ezc3d/files/3730342/BTS_C3Ds.zip)

I attach samples of the original c3d exported with TDF Inspector and the result of doing:
```python
import ezc3d
a = ezc3d.c3d("original.c3d")
a.write("ezc3d.c3d")
```

Checked both files with Mokka. As you said, force platform analogs are not recognized as force platforms, and some of the metadata is mangled (EMG channel description, for example). Is this related to this issue?

**Comment by pariterre** [comment]
Hi @marnunez 
It seems that you are using a previous version of `ezc3d` (I sent a major fix last week). The previous version could explain why it mixes the channel description. Could you try the version 1.2.0?

**Comment by marnunez** [comment]
I'm using ezc3d-1.2.0py37h79cbd7a_0  from conda-forge

**Comment by pariterre** [comment]
ok... That is strange since the ezc3d.c3d file that it creates here doesn't resemble the one you produced :S
I'll look into it!

**Comment by marnunez** [comment]
I've just build ezc3d from master, and tried the same with the Qualisys.c3d, the only one with force platforms, same result.

Before...
![original](https://user-images.githubusercontent.com/1470552/67014710-aba11a00-f0cb-11e9-926d-a26137f68255.png)
After.. Force platforms gone
![after](https://user-images.githubusercontent.com/1470552/67014820-e014d600-f0cb-11e9-8093-e62bafe80657.png)

```python
import ezc3d
a = ezc3d.c3d("Qualisys.c3d")
a.write("Qualisys_after.c3d")
```

Can you reproduce this? I figured out the gtest part, if you're interesed I'll make a PR adding some BTS tests.

**Comment by pariterre** [comment]
@marnunez 
I don't understand where the difference come from... I actually looked at the generated binary versus the original and they are almost identical (except for irrelevant stuff like EZC3D version). However, when I compare to the one you provided me, it definitely looks like a generated c3d from an older version of EZC3D. Are you sure which version you are using? The last version should add the ezc3d version in the c3d file.

I'll try to find a Windows computer so I can test the resulting c3d with mokka

Sorry about that! That puzzles me greatly!

**Comment by marnunez** [comment]
Double checked it. Built from master on a new conda env, on a Windows 10 machine that never had ezc3d.

![imagen](https://user-images.githubusercontent.com/1470552/67059540-e8066180-f12f-11e9-8603-98a9f0a73b83.png)

**Comment by marnunez** [comment]
Same with new build on a Debian sid using g++

![imagen](https://user-images.githubusercontent.com/1470552/67060717-50efd880-f134-11e9-9aed-4f5e2d8714a3.png)

Mokka seems to work ok in wine, if you don't want to switch to Windows.

**Comment by pariterre** [comment]
Nothing special has been done in regard to this, but the C3D are now compliant, so nothing more should be done
