### ISSUE TITLE
Cant install ezc3d module always get error

### ISSUE THREAD

**Issue by redcat22** [pyomeca/ezc3d#47]
Hi 

Thank you very much for the amazing job that you are doing with this project I was a user of btk in matlab but now I am in pyton 3 and btk simply dont work. This certanally will be very important for many people. 

I have conda 3 installed in pc and try to get this module using the indications from here:
https://anaconda.org/conda-forge/ezc3d

and also doing this:   conda install -c pyomeca ezc3d       but always get the following error: 

Any help would me apreciated.
 

PackagesNotFoundError: The following packages are not available from current channels:

  - ezc3d

Current channels:

  - https://conda.anaconda.org/conda-forge/win-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-32
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-32
  - https://repo.anaconda.com/pkgs/msys2/noarch

**Comment by pariterre** [comment]
Hello there!

I hope ezc3d will suit your needs well :)
I maybe forgot to change my ReadMe. Pyomeca no longer hosts ezc3d, it is directly in conda-forge!
So the install line should read : 
conda install -c conda-forge ezc3d

Hope this will help!

**Comment by pariterre** [comment]
Yep, I forgot to update the ReadMe, it is done now ;)

**Comment by redcat22** [comment]
Hi, 

No that dont work too I also tested with these and none worked:

conda install -c conda-forge ezc3d
conda install -c conda-forge/label/gcc7 ezc3d
conda install -c conda-forge/label/cf201901 ezc3d

**Comment by melund** [comment]
@redcat22 It works for me. But I suspect you have a 32bit version of Anaconda. Conda-forge has dropped support for 32-bit versions. So unless you have a very old computer, you could try to install the 64-bit version of Anaconda.

**Comment by pariterre** [comment]
Oh that makes sense, since all the channels he is plugged into are win-32-bit channels.

If you need to use a 32-bit python, you will have to compile ezc3d by yourself. Using CMake and visual studio, it should compile smoothly :)

**Comment by redcat22** [comment]
Hi all,

Thank you for the help. I already solved the problem. In fact I had a python 2.7 32 and python 3.7 64 bits but try to install it in the 3.7 version but some issue occour. I uninstall all the pythons and installed miniconda an now is working. 

thanks once again.
