### ISSUE TITLE
Is there a simple method to get the XYZ coordinates of each marker?

### ISSUE THREAD

**Issue by redcat22** [pyomeca/ezc3d#51]
In matlab using btk I was able to get the coordinates simply by doing this: 

acq = btkReadAcquisition(C3DFilePath);   % returns a handle to Retrieve C3DDada
XYZ = btkGetMarkers(acq);               % get the XY and Z coordinates of each marker. 

I was wonder if in python I can achive something similar? If not what would be the best aproch to get only the XYZ coordinates of each marker? Assuming that we don't know beforehand the name of the markers.

**Comment by pariterre** [comment]
Yep, 
You can use the accessor function:
data = c3d.get_points()

:)

**Comment by pariterre** [comment]
Hello again!
Please note that the pyomeca toolbox may be of great help too :)

**Comment by redcat22** [comment]
Hi pariterre,
Iam new to python and might be missing something but Iam not finding the get_points() 
what  I am doing is:

from ezc3d import c3d
acq = c3d(FilePath)  

then from acq  I only get: 
Data
Header
Parameter
add_parameter
c3d_swig
write
__base__
__bases__
__class__
__init__

I am missing something here? Can you detail a little more how to get the coordinates please.

**Comment by pariterre** [comment]
Hi redcat22!

Sorry I was highly unclear (because I was on my phone...). I've made an accessor for data, but I notice just right now, that it is not so obvious that it exists! I'll improve that in a near future. 

Right now, it is "hidden" in the swig functions (for speed sake, I wrote the parsing command directly in c++, that is why it is there). So here is a minimal example (that I will copy to the ReadMe soon) : 

```python
from ezc3d import c3d
acq = c3d('my_favorite_c3d.c3d')
data = acq.c3d_swig.get_points()
```

'data' is then a numpy array of (4xNxt) where 4 are the component (X, Y, Z, 1) [the 1 is there so you can use rototranslation matrices], the N is the number of points (usually markers, but if you analyzed with Vicon, you will find angles as well, for example), and t is the time frame. Hence if you are interested in the frames 100 to 199, of the markers 3, 4, 6, you should do use the slicing command:
```python
subset = data[:, [3, 4, 6], 100:200]
```

I hope this helps!

**Comment by redcat22** [comment]
Thank you. I am trying to get several parameters from c3d into python therefore after this done if you want I can send you the code which might be used as a guide about how to access some c3d parameters in python and might help others.

cheers

**Comment by pariterre** [comment]
That would be awesome :)

**Comment by romainmartinez** [comment]
Hi @redcat22 ! As pariterre mentioned, we designed [`pyomeca`](https://github.com/pyomeca/pyomeca) to work well with c3d. Pyomeca use ezc3d internally, but abstract from the user some low level functions.

We have some [tutorials](https://github.com/pyomeca/tutorials) to get you started.

For example:
```python
from pyomeca import Markers3d

data_path = 'your_data.c3d'
data = Markers3d.from_c3d(data_path)

# plot the data
data.plot()

# get rate
data.get_rate

# get labels
data.get_labels

# get num frames
data.get_last_frame
```

**Comment by pariterre** [comment]
Oh!
I actually misguided you, I designed c3d_swig.get_points() to be internal only. 

The easy accessor is via the dictionary : 
```python
import ezc3d
acq = ezc3d.c3d("my_favorite_c3d.c3d")
data = acq['data']['points']
```
Then you can slice the data the same way I showed before.

I thought it was bizarre that I did not provided such interface! I added this to the example in the ReadMe :)

Sorry about that!

**Comment by redcat22** [comment]
thank you romainmartinez and pariterre. 

pariterre note that c3d_swig.get_points() is working


I also attached something that can help others. 
The code is not perfect but I believe that can help others. It covers almost all the parameters.
[C3DData.zip](https://github.com/pyomeca/ezc3d/files/2970281/C3DData.zip)

Edited to add a more robust python code file

**Comment by hmok** [comment]
These codes are cool @redcat22. Thanks @pariterre  as well.

**Comment by pariterre** [comment]
So you know, @redcat22 I've included your example in the example folder!

Thanks for your contribution :)
