### ISSUE TITLE
Cannot read c3d files created by Xsens software

### ISSUE THREAD

**Issue by Fiverdug** [pyomeca/ezc3d#52]
Hi,
I'm trying to read c3d files created by MVN (software provided by Xsens) but I get the following error message:
Unexpected Standard exception from MEX file.
What() is:Group::parameterIdx could not find RATE in the group ANALOG
Thanks for your help!

**Comment by pariterre** [comment]
That is due to the absence of mandatory ANALOG parameter. I've created a fix so C3D can be read anyway.

Thanks for reporting!

**Comment by pariterre** [comment]
Version 0.3.6 is now out :)
Enjoy!
