### ISSUE TITLE
eac3d vs. BTK

### ISSUE THREAD

**Issue by hmok** [pyomeca/ezc3d#57]
Hi guys,

I notice you have good examples in Python to use ezc3d. I am just wondering if you may have more detailed tutorial that may have compared the commands with BTK ones. I can relate many of them but It would be great if I could quickly find them and make changes to codes I have based on BTK.

Any suggestion would be appreciated.

Cheers,
Hossein

**Comment by pariterre** [comment]
Hi Hossein!
There is an ezc3d user on #51 (look for the last comment) that produced an top interface that looks like the BTK library. You may have a look. I was considering adding it in the example folder, but I wasn't sure of the relevance to have a BTK like interface. I you think that it is useful, I can integrate the example in my example folder :)

**Comment by hmok** [comment]
Hi Pariterre,

That is great.The link is also very helpful. Thank you.

It would be very useful, I guess, because I think many people who have been using BTK would switch easier when they can see this integration in the examples. It is again up to you. Thanks again!

Cheers,
Hossein

**Comment by pariterre** [comment]
I added it to the example folder!
