### ISSUE TITLE
Setting names for columns and rows

### ISSUE THREAD

**Issue by Dareczin** [pyomeca/ezc3d#59]
Hi!

I am quite new to python and I mostly deal with c3d files with mokka. I have captured kicks for my research and I have many markers and analog data to analyze. For now I got tired exporting every marker to txt using mokka and doing computing in excel and I am looking forward to do it faster. I copy pasted read code from instruction but it gave me nothing. Should I specify exact names of parameters/analog etc to read a file with columns? I am using Jupyter Notebook for this purpose (python usage). I find this instruction insufficient for a noob like me and I will very much appreciate a help with this topic. I tried to attach example of my c3d file but github does not support this file as attachment. Could you help me with specifics?

**Comment by pariterre** [comment]
Hi there!
I am happy to see ezc3d community is growing! I am looking forward to improve the help as well :)

Can you paste the script you are using so I can spot if you are doing something wrong? If not, I will give you my email so you can send me a c3d sample!

**Comment by Dareczin** [comment]
Please give me your mail. My mail is dariusz.mosler@gmail.com - i will send you you example of c3d file. There is no code for now, i just tried copypaste code for python from documentation and it gave me othing wile loading a file. But loading was succesful, becouse I tried muliple files and retur was like some numbers 192, 198 etc, but it indicates that it was reading some data. I am really eager to learn this. I feel that it will be more powerful than octave algorithm to find peak velocity of a kick that I am using right now.

**Comment by Dareczin** [comment]
I found your example. Forgive me for my previous ignorance, it was late at
night and I did not put enough effort. I will try harder based on what you
already contributed in examples of btk_like_example.py

niedz., 26 maj 2019 o 01:04 Pariterre <notifications@github.com> napisał(a):

**Comment by pariterre** [comment]
Hi @dareczin!
No worries! If I may, you should have a look to pyomeca which is a biomechanics library that I write with @romainmartinez. It uses ezc3d under the hood for reading c3d files, but offers plenty of interesting analysing tools for markers and analogs analyses

**Comment by Dareczin** [comment]
Thank you very much! This looks promising, I will look into it.

Best regards,
Dareczin

niedz., 26 maj 2019 o 14:43 Pariterre <notifications@github.com> napisał(a):

**Comment by pariterre** [comment]
Hi there,
Related to the mail you sent me, I strongly suggest using pyomeca :)
In order to compute the derivative, you can use the derivative function (twice if you need the acceleration). Plus, to find peaks, @romainmartinez wrote a ```detect_onset``` function that can help. Also, you can easily plot your time frame data (assuming matplotlib is installed) using ```plot``` method. Finally, there are a lot of filters implemented (moving average, fft, butterworth, etc.). Here is a short example:

```python
from matplotlib import pyplot as plt
import pyomeca

# Load data
markers = pyomeca.Markers3d.from_c3d('./B0264_dollyo_air_P_T01 (1).c3d')/1000
markers_speed = markers.derivative()

# Print some metadata
print(f"Frame one is {markers.get_first_frame} and last frame is {markers.get_last_frame}")
print(f"There is {markers.get_num_markers()} markers.")
print(f"Marker names are : {markers.get_labels}")

# Plot data
markers.plot(fmt='')  # defaul fmt='k' makes everything black which is sometime too sad to look at!
markers_speed.plot(fmt='')
plt.show()
```

**Comment by Dareczin** [comment]
I could not express my graditude, that you were willing to put the effort
to help me. I have installed pyomeca, and there is no error with importing
it, but unfortunetly I get this:

ValueError                                Traceback (most recent call
last)<ipython-input-2-cd3821c785d2> in <module>      4 # Load data
 5 markers = pyomeca.Markers3d.from_c3d('./B0264_dollyo_pilka_L_T01.c3d')/1000---->
6 markers_speed = markers.derivative()      7       8 # Print some
metadata
~\Anaconda3\lib\site-packages\pyomeca\frame_dependent.py in
derivative(self, window)    927         deriv[:, :, -window:] = np.nan
   928         deriv[:, :, window:-window] = (self[:, :, 2 * window:]
- self[:, :, 0:-2 * window]) / (--> 929
self.get_time_frames[2 * window:] - self.get_time_frames[0:-2 *
window])    930         return deriv    931
ValueError: operands could not be broadcast together with shapes
(4,192,4342) (4341,)


niedz., 26 maj 2019 o 21:46 Pariterre <notifications@github.com> napisał(a):

**Comment by pariterre** [comment]
Oh Sorry!
That is an error I solved earlier today, but forgot to send the fix!
Did you installed it via "conda" or manually using "python setup.py install"? (Depending on how you installed it, I will have to send the fix at different places)

**Comment by Dareczin** [comment]
I used conda

niedz., 26 maj 2019 o 22:57 Pariterre <notifications@github.com> napisał(a):

**Comment by pariterre** [comment]
Ok!
I wait for the approval of my pull request from @romainmartinez and then I send the fix on conda!

**Comment by Dareczin** [comment]
I will be up for some time, but maybe I will try it tommorow. Perhaps we
have differences in timezone (I am from Poland). Do you have idea how to
get time of a kick? Like storing max peak values and min values for those
peaks and then computing time of a kick? In pandas, beside values getting
messy with for example 1.4000e-7 I it do not get me the timeframe of
occurance. I am noob here and I only get the general idea what I want to
do.

For other hand, I saw that while using someone's code from github, some
folks want to put their github login as references, how do I post your
effort in my future paper to have some values for you?

niedz., 26 maj 2019 o 23:17 Pariterre <notifications@github.com> napisał(a):

**Comment by pariterre** [comment]
I am from Québec (GTM-5), so huge timezone difference ;)

To get time frames, assuming you know the idx of peaks, you can simply use the "get_time_frame" method provided by pyomeca 
```python
total_time = markers.get_time_frames[idx_end] - markers.get_time_frames[idx_start]
```
I suggest that you have a look at the all the getter provided by pyomeca :)

**Comment by romainmartinez** [comment]
Hi there,

I recommend that you spend some time reading and experimenting with the [pyomeca tutorials](https://github.com/pyomeca/tutorials).

My typical workflow with pyomeca is as follows:

```python
from pathlib import Path
from pyomeca import Analogs3d
import pandas as pd

# Let's say your data is in the `data` directory, where each participant has his own folder
data_path = Path("data")

# first read each file and append them in a list
data_list = []
for ifile in data_path.glob("*/*.c3d"):
    data_list.append(
        # reading a file
        Analogs3d.from_sto(ifile)
        # Some signal processing steps you want
        .time_normalization()
        # convert to pandas dataframe
        .to_dataframe().assign(filename=ifile.stem)
    )

# concat all dataframes into one
data = pd.concat(data_list).reset_index()
```
Which can be written in a more compact way:

```python
data = pd.concat(
    [
        Analogs3d.from_c3d(ifile)
        .time_normalization()
        .to_dataframe()
        .assign(filename=ifile.stem)
        for ifile in data_path.glob("*/*.c3d")
    ]
).reset_index()
```
I like to use the time series and biomechanics specific functions implemented in pyomeca and then transform the data into a big pandas dataframe. Then it is easy to use visualizations (altair, seaborn) and statistics (statsmodel, pymc3) packages.

> For other hand, I saw that while using someone's code from github, some
folks want to put their github login as references, how do I post your
effort in my future paper to have some values for you?

While waiting for us to write a paper, you can simply mention that you used pyomeca/ezc3d. We appreciate citations as these libraries are developed in our free time, but it is not mandatory.

> I wait for the approval of my pull request from @romainmartinez and then I send the fix on conda!

I'll look into it right now!

**Comment by Dareczin** [comment]
Thank you very much! It is working. Now I need to go back to pandas and
other tutorials. I owe you a lot.

Best regards,
Darek

pon., 27 maj 2019, 00:40 użytkownik Romain Martinez <
notifications@github.com> napisał:

**Comment by pariterre** [comment]
@Dareczin 
For your information, pyomeca is now hosted on conda-forge. Therefore, the installation of pyomeca should be using the conda-forge channel instead of the pyomeca channel :  
```bash
conda install pyomeca -c conda-forge
```
Enjoy!

**Comment by Dareczin** [comment]
Hi!

I used that method when you recommend that library for the first timet to
me:)

Slowly I am trying new things. I work 10h/day as physiotherapist so not
much mana left for each day for learining. The picture of data I sent in
previous massage gave me this type of data:

Index(['index', 'Force.Fx1', 'Force.Fx2', 'Force.Fy1', 'Force.Fy2',
       'Force.Fz1', 'Force.Fz2', 'Fx1', 'Fx2', 'Fy1', 'Fy2', 'Fz1', 'Fz2',
       'L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'L7', 'L8', 'Moment.Mx1',
       'Moment.Mx2', 'Moment.My1', 'Moment.My2', 'Moment.Mz1', 'Moment.Mz2',
       'Mx1', 'Mx2', 'My1', 'My2', 'Mz1', 'Mz2', 'R10', 'R11', 'R12', 'R13',
       'R14', 'R15', 'R16', 'R9', 'Voltage.1', 'Voltage.10', 'Voltage.11',
       'Voltage.12', 'Voltage.13', 'Voltage.14', 'Voltage.15', 'Voltage.16',
       'Voltage.2', 'Voltage.3', 'Voltage.4', 'Voltage.5', 'Voltage.6',
       'Voltage.7', 'Voltage.8', 'Voltage.9', 'filename'],
      dtype='object')


But when I export data from mokka I also have points and markers
(picture in attachment). I tried change Points/Markers.from_c3d(ifile)
but it is NameError: name 'Points' is not defined.


If this is in tutorials (I just open some for couple of minutes) do
not bother to explain it, just scold me that this is in the training
materials:P


Best regards,

Darek



wt., 28 maj 2019, 21:54 użytkownik Pariterre <notifications@github.com>
napisał:

**Comment by pariterre** [comment]
> But when I export data from mokka I also have points and markers (picture in attachment). I tried change Points/Markers.from_c3d(ifile) but it is NameError: name 'Points' is not defined.

It seems you are using ```pyomeca``` good for you ;) 
If so, the keyword is not ```Markers``` but ```Markers3d```
So very similar to what romain told you before with this replacing ```Analogs3d``` occurrences 

That should solve your problem :)

**Comment by Dareczin** [comment]
This is the same result

from pathlib import Path
from pyomeca import Analogs3d
import pandas as pd
data_path = Path("data")

data = pd.concat(
    [
        Markers3d.from_c3d(ifile)
        .time_normalization()
        .to_dataframe()
        .assign(filename=ifile.stem)
        for ifile in data_path.glob("*/*.c3d")
    ]
).reset_index()

#####

NameError                                 Traceback (most recent call
last)<ipython-input-12-d811638150c7> in <module>     10
.to_dataframe()     11         .assign(filename=ifile.stem)---> 12
    for ifile in data_path.glob("*/*.c3d")     13     ]     14
).reset_index()
<ipython-input-12-d811638150c7> in <listcomp>(.0)     10
.to_dataframe()     11         .assign(filename=ifile.stem)---> 12
    for ifile in data_path.glob("*/*.c3d")     13     ]     14
).reset_index()
NameError: name 'Markers3d' is not defined



wt., 28 maj 2019 o 22:43 Pariterre <notifications@github.com> napisał(a):

**Comment by pariterre** [comment]
You forgot to import it in the header
```python
from pyomeca import Analogs3d, Markers3d
```

**Comment by Dareczin** [comment]
Dumb me:P

I got something like this:

Index(['index', 'B0264:C7_X', 'B0264:C7_Y', 'B0264:C7_Z', 'B0264:CLAV_X',
       'B0264:CLAV_Y', 'B0264:CLAV_Z', 'B0264:CentreOfMassFloor_X',
       'B0264:CentreOfMassFloor_Y', 'B0264:CentreOfMassFloor_Z',
       ...
       'TRXP_X', 'TRXP_Y', 'TRXP_Z', 'Tarcza:T1_X', 'Tarcza:T1_Y',
       'Tarcza:T1_Z', 'Tarcza:T2_X', 'Tarcza:T2_Y', 'Tarcza:T2_Z', 'filename'],
      dtype='object', length=2930)

Still cannot find toe marker column

wt., 28 maj 2019 o 23:05 Pariterre <notifications@github.com> napisał(a):

**Comment by pariterre** [comment]
What is the name of the Toe marker? Because it seems that these are actual markers... That would be surprising they are not in this vector.. (Just in case, please note that the "..." refers to the fact that not everything in the vector is listed)

**Comment by Dareczin** [comment]
I am interested mostly in ltoe or rtoe markers (i am sending picture from
mokka). But if im calling data.colums, they should listed me every columnt
that was created, am I correct?

As you can see in the mokka editon of those c3d files there are plenty of
markers registered but markers3d did not return it in panadas series.



wt., 28 maj 2019 o 23:15 Pariterre <notifications@github.com> napisał(a):

**Comment by pariterre** [comment]
Actually, since you writting on GitHub, the figures are removed ;)

> But if im calling data.colums, they should listed me every columnt that was created, am I correct?

Yep, but for saving space, Python show the first and last elements while the one in middle are skipped. If I recall well, ```print(your_list)``` shows every element of the list

**Comment by pariterre** [comment]
The following code should list all the markers without skipping any.
```python
import pyomeca
c = pyomeca.Markers3d.from_c3d('your_c3d_file.c3d')
c.get_labels
```

**Comment by Dareczin** [comment]
YES! This worked!

['LFHD',
 'RFHD',
 'LBHD',
 'RBHD',
 'C7',
 'T10',
 'CLAV',
 'STRN',
 'RBAK',
 'LSHO',
 'LUPA',
 'LELB',
 'LFRM',
 'LWRA',
 'LWRB',
 'LFIN',
 'RSHO',
 'RUPA',
 'RELB',
 'RFRM',
 'RWRA',
 'RWRB',
 'RFIN',
 'LASI',
 'RASI',
 'LPSI',
 'RPSI',
 'LTHI',
 'LKNE',
 'LTIB',
 'LANK',
 'LHEE',
 'LTOE',
 'RTHI',
 'RKNE',
 'RTIB',
 'RANK',
 'RHEE',
 'RTOE',
 'CentreOfMass',
 'CentreOfMassFloor',
 'HEDO',
 'HEDA',
 'HEDL',
 'HEDP',
 'LCLO',
 'LCLA',
 'LCLL',
 'LCLP',
 'LFEO',
 'LFEA',
 'LFEL',
 'LFEP',
 'LFOO',
 'LFOA',
 'LFOL',
 'LFOP',
 'LHNO',
 'LHNA',
 'LHNL',
 'LHNP',
 'LHUO',
 'LHUA',
 'LHUL',
 'LHUP',
 'LRAO',
 'LRAA',
 'LRAL',
 'LRAP',
 'LTIO',
 'LTIA',
 'LTIL',
 'LTIP',
 'LTOO',
 'LTOA',
 'LTOL',
 'LTOP',
 'PELO',
 'PELA',
 'PELL',
 'PELP',
 'RCLO',
 'RCLA',
 'RCLL',
 'RCLP',
 'RFEO',
 'RFEA',
 'RFEL',
 'RFEP',
 'RFOO',
 'RFOA',
 'RFOL',
 'RFOP',
 'RHNO',
 'RHNA',
 'RHNL',
 'RHNP',
 'RHUO',
 'RHUA',
 'RHUL',
 'RHUP',
 'RRAO',
 'RRAA',
 'RRAL',
 'RRAP',
 'RTIO',
 'RTIA',
 'RTIL',
 'RTIP',
 'RTOO',
 'RTOA',
 'RTOL',
 'RTOP',
 'TRXO',
 'TRXA',
 'TRXL',
 'TRXP',
 'LHipAngles',
 'LKneeAngles',
 'LAnkleAngles',
 'LAbsAnkleAngle',
 'RHipAngles',
 'RKneeAngles',
 'RAnkleAngles',
 'RAbsAnkleAngle',
 'LShoulderAngles',
 'LElbowAngles',
 'LWristAngles',
 'RShoulderAngles',
 'RElbowAngles',
 'RWristAngles',
 'LNeckAngles',
 'RNeckAngles',
 'LSpineAngles',
 'RSpineAngles',
 'LHeadAngles',
 'RHeadAngles',
 'LThoraxAngles',
 'RThoraxAngles',
 'LPelvisAngles',
 'RPelvisAngles',
 'LFootProgressAngles',
 'RFootProgressAngles',
 'LAnklePower',
 'RAnklePower',
 'LKneePower',
 'RKneePower',
 'LHipPower',
 'RHipPower',
 'LWaistPower',
 'RWaistPower',
 'LNeckPower',
 'RNeckPower',
 'LShoulderPower',
 'RShoulderPower',
 'LElbowPower',
 'RElbowPower',
 'LWristPower',
 'RWristPower',
 'LAnkleForce',
 'RAnkleForce',
 'LKneeForce',
 'RKneeForce',
 'LHipForce',
 'RHipForce',
 'LWaistForce',
 'RWaistForce',
 'LNeckForce',
 'RNeckForce',
 'LShoulderForce',
 'RShoulderForce',
 'LElbowForce',
 'RElbowForce',
 'LWristForce',
 'RWristForce',
 'LAnkleMoment',
 'RAnkleMoment',
 'LKneeMoment',
 'RKneeMoment',
 'LHipMoment',
 'RHipMoment',
 'LWaistMoment',
 'RWaistMoment',
 'LNeckMoment',
 'RNeckMoment',
 'LShoulderMoment',
 'RShoulderMoment',
 'LElbowMoment',
 'RElbowMoment',
 'LWristMoment',
 'RWristMoment']


You are my master now.


wt., 28 maj 2019 o 23:35 Pariterre <notifications@github.com> napisał(a):

**Comment by pariterre** [comment]
Haha, you are welcome.

Good luck for your analyses!

**Comment by Dareczin** [comment]
Thank you very much. I will have to compute time between min signals
and max signals value of velocity (star and hitting a target by kick)
so perhaps I will attack you again if I get to this point without
success.

I wish you good luck with all your projects and thank you for your
patiance my master!

wt., 28 maj 2019 o 23:42 Pariterre <notifications@github.com> napisał(a):
