### ISSUE TITLE
File Size

### ISSUE THREAD

**Issue by claraziane** [pyomeca/ezc3d#60]
Hello,

I am using ezc3d to read files from Vicon on Matlab but files above 45000 frames won't open. I get the following error : 
Unexpected Standard exception from MEX file.
What() is:vector<T> too long
..

Error in OrgData (line 145)
        c3d = ezc3dRead(FileName);

Error in KinRecons_tout_Clara (line 126)
                    recons.TOBS = OrgData([RawPath filesep() files(iFiles).name],conf,false);

I can link you the files.

Thank you very much.

**Comment by pariterre** [comment]
Hi @zianec,
This was due to an architecture decision I have made in the past. I've updated ezc3d so I can take MUCH larger C3D now (Tested on a c3d of 700 Mo). 
Let me know if everything works!

**Comment by claraziane** [comment]
I have tested it for files up to 1.24 GB and it works ! Thank you for the update @pariterre  !

**Comment by pariterre** [comment]
Woot!
