### ISSUE TITLE
Support for integer format in point data

### ISSUE THREAD

**Issue by lasagnaphil** [pyomeca/ezc3d#67]
It seems like the integer format in 3D point data (described in page 57 of the C3D File Format User Guide) is not supported yet. Trying to load files with the integer format currently results in the following error message:
```
Points were recorded using int number which is not implemented yet
```

**Comment by pariterre** [comment]
Dear @lasagnaphil 
Indeed, up to now, I did not have access to an integer format file, so I did not have template to work on. If you could provide me with a file (to my email address), I will implement it soon :)

**Comment by lasagnaphil** [comment]
Sadly, the files that I have cannot be disclosed to others due to strict security/license reasons. But from what I can tell from loading the file with another library (py-c3d): the file seems to be created in a DEC processor (which is pretty old by today's standards, I guess!)

It seems that there are some example files in integer format in the official c3d site: https://www.c3d.org/sampledata.html. (In particular, the test suites, which includes DEC integer formats.)

Anyways, thanks for all the hard work in maintaining this library!
- Phil

**Comment by pariterre** [comment]
Wow interestingly enough, I completely missed that test suit :|
I will focus on DEC, int!

I let you know when it is done :)

**Comment by pariterre** [comment]
@lasagnaphil 
Are you building from the source or you are installing from conda? If it is the former, could you try your files to see if it gives normal values? Otherwise, I will release a new version soon so it will be available from conda (even though I would prefer to confirm this is a working version!)

**Comment by lasagnaphil** [comment]
I’ve installed it from the ArchLinux AUR [PKGBUILD](https://aur.archlinux.org/packages/ezc3d/) (which I’ve modified it manually to use the latest version, v1.01). So basically I’m building from source.

**Comment by pariterre** [comment]
Oh! I did not know it was hosted there!
I am not sure how to update it... I'll create the 1.1.0 release today so you will be able to test :)

**Comment by lasagnaphil** [comment]
I've tried the master branch with the updated PR, and it works like a charm! Thanks for all the work!

As for the PKGBUILD, you don't have to worry about it, since it involves just changing a few lines (like version numbers). I'll later poke a message to the package maintainer to update it to the latest version.

**Comment by pariterre** [comment]
Sweet, so I'll release the next version! I've decided to call it "Nostalgia" because ezc3d is now able to read old fashion c3d haha!
Thanks for the report
