### ISSUE TITLE
Trouble parsing and rebuilding c3Ds with Python bindings

### ISSUE THREAD

**Issue by marnunez** [pyomeca/ezc3d#91]
This is a non exhaustive list of things I found different in the metadata when parsing and rebuilding the Qualisys and BTS c3ds through ezc3d and checked with Mokka

- All field descriptions are somehow gone in the rebuild files
- Most char fields seem to have wrong length informed
- Nested array fields such as CORNERS are seen as nested (e.g.: 3x4x2) in the original, as the sum result (24) in the rebuild file
- Some parameter names are forced into uppercase (this might be intentional)

@pariterre , could this be related to Mokka not displaying correctly the force platforms as discussed in #40 ?

**Comment by pariterre** [comment]
Ok definitely! the CORNERS is definitely the problem here! I can fix that soon :)
For the parameter uppercase, this is indeed intentional since the c3d.org suggests that
Thanks for the spot, I will correct all of these differences ASAP!

**Comment by marnunez** [comment]
Just found out this occurs only with Python, none of this happens with the C++ classes.

**Comment by pariterre** [comment]
Hi @marnunez
PR #90 and #92 should now solves these problem. 
When you confirm you satisfaction, I release the new version on Conda!
Thanks again! :)
