### ISSUE TITLE
Badges and Windows build

### ISSUE THREAD

**Issue by marnunez** [pyomeca/ezc3d#93]
This is not high priority, but might as well have them now before things get more complex. Badges in the readme file might prove useful, could add coverage badge as well. As much as I like Linux, I use Windows at work, like many others. Adding a Windows build would be nice. Travis added recently a windows environment, might be enough. Appveyor could be another option.

**Comment by pariterre** [comment]
Hello!
I am not sure what you mean.. As far as I know, ezc3d is tested for Linux, Windows and Mac by Travis, as well as it is built and distributed for all three platform on conda-forge.

**Comment by marnunez** [comment]
Forget about it, I've been building from source and completely forgot about the conda builds. What I ment by badges is that it might be useful to see at a quick glance when the dev branch is not passing the tests. A travis badge in the readme file, with the link to the project automatic builds.

**Comment by pariterre** [comment]
Ok! Make sense, I'll look into that

**Comment by pariterre** [comment]
Done! Thanks for the comment!
